// Generated by Apple Swift version 4.0.3 effective-3.2.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import BaseClases;
@import UIKit;
@import CoreGraphics;
@import RealmSwift;
@import Foundation;
@import CoreLocation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("prospect")
@class LoginRequest;

SWIFT_CLASS("_TtC8prospect10ACDRequest")
@interface ACDRequest : NSObject
@property (nonatomic, strong) LoginRequest * _Nullable login;
@property (nonatomic, copy) NSString * _Nullable opportunityId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ResultBean;

SWIFT_CLASS("_TtC8prospect11ACDResponse")
@interface ACDResponse : NSObject
@property (nonatomic, strong) ResultBean * _Nullable result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class AddonSelectorPresenter;
@class AddonsCarouselDataSource;
@class BasePresenter;
@class Plans;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC8prospect31AdditionalServiceViewController")
@interface AdditionalServiceViewController : BaseViewController
@property (nonatomic) double mPriceConverted;
@property (nonatomic, strong) AddonSelectorPresenter * _Nullable mAddonSelectorPresenter;
@property (nonatomic, strong) AddonsCarouselDataSource * _Null_unspecified addonsCarouselDataSource;
- (void)viewDidLoad;
- (void)clearData;
- (void)onCalculateTotalAmountWithPriceList:(double)priceList priceSoonPayment:(double)priceSoonPayment;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (IBAction)onNextButtonClick:(id _Nonnull)sender;
- (void)onSuccessLoadPlanWithPlan:(Plans * _Nonnull)plan;
- (void)onCalculateTotalAmountWithPrice:(double)price;
- (void)onSuccessSaveProposalBean;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ArrServiciosIncluidos;
@class PlanDetailResponse;
@class BaseResponse;
@class ArrServiciosAdicionales;
@class ArrProductosAdicionales;

SWIFT_CLASS("_TtC8prospect22AddonSelectorPresenter")
@interface AddonSelectorPresenter : BaseEstrategiaPresenter
@property (nonatomic, strong) Plans * _Null_unspecified mPlanSelected;
@property (nonatomic, copy) NSArray<ArrServiciosIncluidos *> * _Nonnull mArrIncludeServices;
@property (nonatomic) double planSoonPrice;
- (void)loadPlan;
- (void)onRequestWs;
- (void)loadAddons;
- (void)onSuccessAddonsWithPlanDetailResponse:(PlanDetailResponse * _Nonnull)planDetailResponse;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
- (void)onErrorLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl messageError:(NSString * _Nonnull)messageError;
- (void)generateProposalWithArrIncludeServices:(NSArray<ArrServiciosIncluidos *> * _Nonnull)arrIncludeServices addonServicesBean:(NSArray<ArrServiciosAdicionales *> * _Nonnull)addonServicesBean arrAddonProd:(NSArray<ArrProductosAdicionales *> * _Nonnull)arrAddonProd;
@end

@class iCarousel;
@class UIView;

SWIFT_CLASS("_TtC8prospect24AddonsCarouselDataSource")
@interface AddonsCarouselDataSource : NSObject <iCarouselDataSource, iCarouselDelegate>
@property (nonatomic, strong) iCarousel * _Null_unspecified carrusel;
- (void)settings;
- (NSInteger)numberOfItemsInCarousel:(iCarousel * _Nonnull)carousel SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)carousel:(iCarousel * _Nonnull)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView * _Nullable)view SWIFT_WARN_UNUSED_RESULT;
- (void)carousel:(iCarousel * _Nonnull)carousel didSelectItemAtIndex:(NSInteger)index;
- (void)carouselCurrentItemIndexDidChange:(iCarousel * _Nonnull)carousel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect16AddressCPRequest")
@interface AddressCPRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nullable cp;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCp:(NSString * _Nonnull)cp OBJC_DESIGNATED_INITIALIZER;
@end

@class Suburb;

SWIFT_CLASS("_TtC8prospect17AddressCpResponse")
@interface AddressCpResponse : BaseResponse
@property (nonatomic, copy) NSArray<Suburb *> * _Nullable suburbs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class DireccionFacturacionBean;

SWIFT_CLASS("_TtC8prospect20AddressDataPresenter")
@interface AddressDataPresenter : BaseEstrategiaPresenter
- (void)saveDireccionFacturacionBean;
- (void)saveDirecionFacturacionBeanWithDireccionFacturacionBean:(DireccionFacturacionBean * _Nonnull)direccionFacturacionBean;
@end

@class CheckBoxGroup;
@class FormValidator;
@class CheckBoxButton;

SWIFT_CLASS("_TtC8prospect25AddressDataViewController")
@interface AddressDataViewController : BaseEstrategiaViewController
@property (nonatomic, strong) CheckBoxGroup * _Null_unspecified mAddressCheckBoxGroup;
@property (nonatomic, strong) FormValidator * _Null_unspecified mFormValidator;
@property (nonatomic, strong) AddressDataPresenter * _Null_unspecified mAddressDataPresenter;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (void)loadAddressInfo;
- (IBAction)onNextButtonClick:(id _Nonnull)sender;
- (void)onCheckBoxButtonClickWithCheckButton:(CheckBoxButton * _Nonnull)checkButton;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol NSObject;
@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC8prospect17BaseTableViewCell")
@interface BaseTableViewCell : UITableViewCell
@property (nonatomic, strong) id <NSObject> _Null_unspecified delegate;
@property (nonatomic, strong) NSObject * _Nullable itemObject;
- (void)awakeFromNib;
- (void)tapEdit:(UITapGestureRecognizer * _Nonnull)sender;
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (void)pupulateSelectedWithObject:(NSObject * _Nonnull)object;
- (void)executeAction;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect13AdicionalCell")
@interface AdicionalCell : BaseTableViewCell
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect38AditionalServiceCollectionReusableView")
@interface AditionalServiceCollectionReusableView : UICollectionReusableView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect22AditionalTableViewCell")
@interface AditionalTableViewCell : BaseTableViewCell
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class DPServicioProducto;
@class RLMRealm;
@class RLMObjectSchema;
@class RLMSchema;

SWIFT_CLASS("_TtC8prospect32ArrDPPromocionesServicioProducto")
@interface ArrDPPromocionesServicioProducto : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull agregarServicio;
@property (nonatomic, copy) NSString * _Nonnull esCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull estatus;
@property (nonatomic, copy) NSString * _Nonnull iEPS;
@property (nonatomic, copy) NSString * _Nonnull iVA;
@property (nonatomic, copy) NSString * _Nonnull mesInicio;
@property (nonatomic, copy) NSString * _Nonnull montoC;
@property (nonatomic, copy) NSString * _Nonnull planServicio;
@property (nonatomic, copy) NSString * _Nonnull porcentaje;
@property (nonatomic, copy) NSString * _Nonnull productoCaracteristica;
@property (nonatomic, copy) NSString * _Nonnull promocionPlan;
@property (nonatomic, copy) NSString * _Nonnull servicioProducto;
@property (nonatomic, copy) NSString * _Nonnull vigenciaMes;
@property (nonatomic, copy) NSString * _Nonnull idProductoC;
@property (nonatomic, copy) NSString * _Nonnull nameProductoC;
@property (nonatomic, copy) NSString * _Nonnull productoId;
@property (nonatomic, copy) NSString * _Nonnull ciudad;
@property (nonatomic, copy) NSString * _Nonnull velocidadSubida;
@property (nonatomic, copy) NSString * _Nonnull velocidadBajada;
@property (nonatomic, copy) NSString * _Nonnull tieneIPDinamica;
@property (nonatomic, copy) NSString * _Nonnull tieneIPFija;
@property (nonatomic, copy) NSString * _Nonnull tieneSTBAdicional;
@property (nonatomic, copy) NSString * _Nonnull esCCTV;
@property (nonatomic, copy) NSString * _Nonnull esWiFi;
@property (nonatomic, copy) NSString * _Nonnull cantidad;
@property (nonatomic, copy) NSString * _Nonnull estatusProductoC;
@property (nonatomic, copy) NSString * _Nonnull fechaInicio;
@property (nonatomic, copy) NSString * _Nonnull fechaFin;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull esProntoPago;
@property (nonatomic, strong) DPServicioProducto * _Nullable dPServicioProducto;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class ArrPlan;

SWIFT_CLASS("_TtC8prospect9ArrFamily")
@interface ArrFamily : NSObject
@property (nonatomic, copy) NSString * _Nonnull idFamily;
@property (nonatomic, copy) NSString * _Nonnull nameFamily;
@property (nonatomic, copy) NSArray<ArrPlan *> * _Nonnull arrPlan;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect25ArrProductosIncluidosBean")
@interface ArrProductosIncluidosBean : NSObject
@property (nonatomic, copy) NSString * _Nullable Id;
@property (nonatomic, copy) NSString * _Nullable Nombre;
@property (nonatomic, copy) NSString * _Nullable AgrupacionAddon;
@property (nonatomic, copy) NSString * _Nullable CantidadDN;
@property (nonatomic, copy) NSString * _Nullable CantidadTroncal;
@property (nonatomic, copy) NSString * _Nullable Comentario;
@property (nonatomic, copy) NSString * _Nullable EsAutomaticoCiudad;
@property (nonatomic, copy) NSString * _Nullable EsCargoUnico;
@property (nonatomic, copy) NSString * _Nullable Estatus;
@property (nonatomic, copy) NSString * _Nullable EsVisible;
@property (nonatomic, copy) NSString * _Nullable IdBrmArrear;
@property (nonatomic, copy) NSString * _Nullable IdBrmCU;
@property (nonatomic, copy) NSString * _Nullable IdBrmForward;
@property (nonatomic, copy) NSString * _Nullable IEPS;
@property (nonatomic, copy) NSString * _Nullable IVA;
@property (nonatomic, copy) NSString * _Nullable MaximoAgregar;
@property (nonatomic, copy) NSString * _Nullable NombreEditable;
@property (nonatomic, copy) NSString * _Nullable PlanDescuentoId;
@property (nonatomic, copy) NSString * _Nullable Plazo;
@property (nonatomic, copy) NSString * _Nullable PrecioBase;
@property (nonatomic, copy) NSString * _Nullable PrecioEditable;
@property (nonatomic, copy) NSString * _Nullable PrecioProntoPago;
@property (nonatomic, copy) NSString * _Nullable ProductoPadre;
@property (nonatomic, copy) NSString * _Nullable TipoProducto;
@property (nonatomic, copy) NSString * _Nullable IdProducto;
@property (nonatomic, copy) NSString * _Nullable NameProducto;
@property (nonatomic, copy) NSString * _Nullable ProductoId;
@property (nonatomic, copy) NSString * _Nullable Ciudad;
@property (nonatomic, copy) NSString * _Nullable VelocidadSubida;
@property (nonatomic, copy) NSString * _Nullable VelocidadBajada;
@property (nonatomic, copy) NSString * _Nullable TieneIPDinamica;
@property (nonatomic, copy) NSString * _Nullable TieneIPFija;
@property (nonatomic, copy) NSString * _Nullable TieneSTBAdicional;
@property (nonatomic, copy) NSString * _Nullable EsCCTV;
@property (nonatomic, copy) NSString * _Nullable EsWiFi;
@property (nonatomic, copy) NSString * _Nullable Cantidad;
@property (nonatomic, copy) NSString * _Nullable EstatusProducto;
@property (nonatomic, copy) NSString * _Nullable FechaInicio;
@property (nonatomic, copy) NSString * _Nullable FechaFin;
@property (nonatomic, copy) NSString * _Nullable ComentarioProducto;
@property (nonatomic, copy) NSString * _Nullable EsProntoPago;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect26ArrPromocionesConvivencium")
@interface ArrPromocionesConvivencium : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull estatus;
@property (nonatomic, copy) NSString * _Nonnull promocionPlanId;
@property (nonatomic, copy) NSString * _Nonnull promocionExcId;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect21ArrPromocionesDetalle")
@interface ArrPromocionesDetalle : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull cATCanalVenta;
@property (nonatomic, copy) NSString * _Nonnull cATCiudad;
@property (nonatomic, copy) NSString * _Nonnull cATCluster;
@property (nonatomic, copy) NSString * _Nonnull cATPlazo;
@property (nonatomic, copy) NSString * _Nonnull codigoPostal;
@property (nonatomic, copy) NSString * _Nonnull cATTipoPago;
@property (nonatomic, copy) NSString * _Nonnull dPPromocion;
@property (nonatomic, copy) NSString * _Nonnull estatus;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect18ArrPromocionesPlan")
@interface ArrPromocionesPlan : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull descripcion;
@property (nonatomic, copy) NSString * _Nonnull plan;
@property (nonatomic, copy) NSString * _Nonnull planCambioParrilla;
@property (nonatomic, copy) NSString * _Nonnull promocion;
@property (nonatomic, copy) NSString * _Nonnull estatus;
@property (nonatomic, copy) NSString * _Nonnull plazo;
@property (nonatomic, copy) NSString * _Nonnull estatusPromociones;
@property (nonatomic, copy) NSString * _Nonnull comentarioPromocion;
@property (nonatomic, copy) NSString * _Nonnull nombrePromocion;
@property (nonatomic, copy) NSString * _Nonnull companiaId;
@property (nonatomic, copy) NSString * _Nonnull esAutomatica;
@property (nonatomic, copy) NSString * _Nonnull esPostVenta;
@property (nonatomic, copy) NSString * _Nonnull estatusPromocion;
@property (nonatomic, copy) NSString * _Nonnull esVentaNueva;
@property (nonatomic, copy) NSString * _Nonnull fechaFin;
@property (nonatomic, copy) NSString * _Nonnull fechaInicio;
@property (nonatomic, copy) NSString * _Nonnull idPromocion;
@property (nonatomic) BOOL isSelected;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class ArrProductosIncluido;

SWIFT_CLASS("_TtC8prospect23ArrServiciosAdicionales")
@interface ArrServiciosAdicionales : NSObject
- (NSString * _Nonnull)getID SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getAdicionalType SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAdicionalName SWIFT_WARN_UNUSED_RESULT;
- (double)getPrecioBase SWIFT_WARN_UNUSED_RESULT;
- (double)getPrecioProntoPago SWIFT_WARN_UNUSED_RESULT;
- (double)getCantidad SWIFT_WARN_UNUSED_RESULT;
- (double)getIVA SWIFT_WARN_UNUSED_RESULT;
- (double)getIEPS SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull cantidadEquiposAutomaticos;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull maximoAgregar;
@property (nonatomic, copy) NSString * _Nonnull nombrecomercial;
@property (nonatomic, copy) NSString * _Nonnull nombreEditable;
@property (nonatomic, copy) NSString * _Nonnull planId;
@property (nonatomic, copy) NSString * _Nonnull precio;
@property (nonatomic, copy) NSString * _Nonnull seActiva;
@property (nonatomic, copy) NSString * _Nonnull seFactura;
@property (nonatomic, copy) NSString * _Nonnull servicioId;
@property (nonatomic, copy) NSString * _Nonnull sRVMode;
@property (nonatomic, copy) NSString * _Nonnull tipoServicio;
@property (nonatomic, copy) NSString * _Nonnull tipoTelefonia;
@property (nonatomic, copy) NSString * _Nonnull priceApp;
@property (nonatomic, copy) NSString * _Nonnull image;
@property (nonatomic, copy) NSArray<ArrProductosIncluido *> * _Nonnull arrProductosIncluidos;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect21ArrServiciosIncluidos")
@interface ArrServiciosIncluidos : NSObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull cantidadEquiposAutomaticos;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull maximoAgregar;
@property (nonatomic, copy) NSString * _Nonnull nombrecomercial;
@property (nonatomic, copy) NSString * _Nonnull nombreEditable;
@property (nonatomic, copy) NSString * _Nonnull planId;
@property (nonatomic, copy) NSString * _Nonnull precio;
@property (nonatomic, copy) NSString * _Nonnull seActiva;
@property (nonatomic, copy) NSString * _Nonnull seFactura;
@property (nonatomic, copy) NSString * _Nonnull servicioId;
@property (nonatomic, copy) NSString * _Nonnull sRVMode;
@property (nonatomic, copy) NSString * _Nonnull tipoServicio;
@property (nonatomic, copy) NSString * _Nonnull tipoTelefonia;
@property (nonatomic, copy) NSArray<ArrProductosIncluido *> * _Nonnull arrProductosIncluidos;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect25ArrServiciosIncluidosBean")
@interface ArrServiciosIncluidosBean : NSObject
@property (nonatomic, copy) NSString * _Nullable Id;
@property (nonatomic, copy) NSString * _Nullable Nombre;
@property (nonatomic, copy) NSString * _Nullable CantidadEquiposAutomaticos;
@property (nonatomic, copy) NSString * _Nullable Comentario;
@property (nonatomic, copy) NSString * _Nullable MaximoAgregar;
@property (nonatomic, copy) NSString * _Nullable Nombrecomercial;
@property (nonatomic, copy) NSString * _Nullable NombreEditable;
@property (nonatomic, copy) NSString * _Nullable PlanId;
@property (nonatomic, copy) NSString * _Nullable Precio;
@property (nonatomic, copy) NSString * _Nullable SeActiva;
@property (nonatomic, copy) NSString * _Nullable SeFactura;
@property (nonatomic, copy) NSString * _Nullable ServicioId;
@property (nonatomic, copy) NSString * _Nullable SRV_Mode;
@property (nonatomic, copy) NSString * _Nullable TipoServicio;
@property (nonatomic, copy) NSString * _Nullable TipoTelefonia;
@property (nonatomic, copy) NSArray<ArrProductosIncluidosBean *> * _Nonnull ArrProductosIncluidos;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Imagen;

SWIFT_CLASS("_TtC8prospect17AttachmentRequest")
@interface AttachmentRequest : NSObject
@property (nonatomic, copy) NSString * _Nonnull opportunityId;
@property (nonatomic, copy) NSString * _Nonnull brmAccount;
@property (nonatomic, copy) NSArray<Imagen *> * _Nonnull images;
- (nonnull instancetype)initWithOpportunityId:(NSString * _Nonnull)opportunityId brmAccount:(NSString * _Nonnull)brmAccount image:(Imagen * _Nonnull)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC8prospect26CapturePhotoViewController")
@interface CapturePhotoViewController : BaseViewController
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (IBAction)mCaptureButton:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class CardIOCreditCardInfo;
@class CardIOPaymentViewController;

SWIFT_CLASS("_TtC8prospect27CardMethodPayViewController")
@interface CardMethodPayViewController : BaseViewController <CardIOPaymentViewControllerDelegate>
@property (nonatomic, strong) CardIOCreditCardInfo * _Null_unspecified mCardInfo;
@property (nonatomic, strong) FormValidator * _Null_unspecified mFormValidator;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull mContactTye;
@property (nonatomic, copy) NSString * _Nullable mTypeIconCard;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (IBAction)mSaveButton:(id _Nonnull)sender;
- (IBAction)mDueDateTextField:(id _Nonnull)sender;
- (IBAction)mScanCardButton:(id _Nonnull)sender;
- (void)userDidCancelPaymentViewController:(CardIOPaymentViewController * _Null_unspecified)paymentViewController;
- (void)userDidProvideCreditCardInfo:(CardIOCreditCardInfo * _Null_unspecified)cardInfo inPaymentViewController:(CardIOPaymentViewController * _Null_unspecified)paymentViewController;
- (void)validateTypeCardWithNumberCard:(NSString * _Nonnull)numberCard;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect18CarruselDataSource")
@interface CarruselDataSource : NSObject <iCarouselDataSource, iCarouselDelegate>
@property (nonatomic, strong) iCarousel * _Nonnull mICarousel;
@property (nonatomic, copy) NSArray<Plans *> * _Nonnull mItems;
@property (nonatomic) NSInteger mSelectedIndex;
- (void)settings;
- (void)updateWithItems:(NSArray<Plans *> * _Nonnull)items;
- (NSInteger)numberOfItemsInCarousel:(iCarousel * _Nonnull)carousel SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)carousel:(iCarousel * _Nonnull)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView * _Nullable)view SWIFT_WARN_UNUSED_RESULT;
- (void)carousel:(iCarousel * _Nonnull)carousel didSelectItemAtIndex:(NSInteger)index;
- (void)carouselCurrentItemIndexDidChange:(iCarousel * _Nonnull)carousel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect27CashMethodPayViewController")
@interface CashMethodPayViewController : BaseEstrategiaViewController
@property (nonatomic, strong) FormValidator * _Null_unspecified mFormValidator;
- (void)viewDidLoad;
- (IBAction)mSaveButton:(id _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect26CellDirectionTableViewCell")
@interface CellDirectionTableViewCell : BaseTableViewCell
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect14CheckBoxButton")
@interface CheckBoxButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)handleTap:(UITapGestureRecognizer * _Nullable)sender;
@property (nonatomic) BOOL isChecked;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect13CheckBoxGroup")
@interface CheckBoxGroup : NSObject
@property (nonatomic, copy) NSArray<CheckBoxButton *> * _Null_unspecified checksBox;
@property (nonatomic, strong) CheckBoxButton * _Nullable checkBoxSelected;
- (void)handleTap:(CheckBoxButton * _Nullable)sender;
- (void)setCheckWithCheckBox:(CheckBoxButton * _Nonnull)checkBox;
- (NSString * _Nullable)getValue SWIFT_WARN_UNUSED_RESULT;
- (void)setValueWithValue:(NSString * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class DireccionBean;
@class ReferidoBean;
@class VendedorBean;

SWIFT_CLASS("_TtC8prospect24ConfirmLocationPresenter")
@interface ConfirmLocationPresenter : BaseEstrategiaPresenter
@property (nonatomic, strong) DireccionBean * _Null_unspecified mDireccionBean;
- (void)loadDireccionBean;
- (void)confirmDirrecionBeanWithDireccionBean:(DireccionBean * _Nonnull)direccionBean;
- (ReferidoBean * _Nonnull)generateReferenciaBean SWIFT_WARN_UNUSED_RESULT;
- (VendedorBean * _Nonnull)generateVendedorBean SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8prospect29ConfirmLocationViewController")
@interface ConfirmLocationViewController : BaseViewController
@property (nonatomic, strong) FormValidator * _Null_unspecified mFormValidator;
@property (nonatomic, strong) ConfirmLocationPresenter * _Null_unspecified mConfirmLocationPresenter;
- (void)viewDidLoad;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (IBAction)nextButton:(id _Nonnull)sender;
- (void)onSuccessLoadDireccionBeanWithDireccionBean:(DireccionBean * _Nonnull)direccionBean;
- (void)onSuccessSaveDireccionBean;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class SendOpportunityPresenter;

SWIFT_CLASS("_TtC8prospect25ContractingViewController")
@interface ContractingViewController : BaseEstrategiaViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_ADD_CONTACT_INFO;)
+ (NSString * _Nonnull)REQUEST_CODE_ADD_CONTACT_INFO SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_ADD_CONTACT_INFO:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_ADD_PERSON_INFO;)
+ (NSString * _Nonnull)REQUEST_CODE_ADD_PERSON_INFO SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_ADD_PERSON_INFO:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_ADD_ADDRESS_INFO;)
+ (NSString * _Nonnull)REQUEST_CODE_ADD_ADDRESS_INFO SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_ADD_ADDRESS_INFO:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_ADD_DOCUMENTS_INFO;)
+ (NSString * _Nonnull)REQUEST_CODE_ADD_DOCUMENTS_INFO SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_ADD_DOCUMENTS_INFO:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_ADD_METHOD_PAYMENT_INFO;)
+ (NSString * _Nonnull)REQUEST_CODE_ADD_METHOD_PAYMENT_INFO SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_ADD_METHOD_PAYMENT_INFO:(NSString * _Nonnull)value;
@property (nonatomic) BOOL mSuccessCaptureContactInfo;
@property (nonatomic) BOOL mSuccesCapturePaymentInfo;
@property (nonatomic, strong) SendOpportunityPresenter * _Null_unspecified mSendOpportunityPresenter;
- (void)viewDidLoad;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (IBAction)mContactInfoButton:(id _Nonnull)sender;
- (void)successCaptureContactoInfo;
- (void)successCapturePaymentInfo;
- (IBAction)mPaymentButton:(id _Nonnull)sender;
- (IBAction)onSendOpportunityClick:(id _Nonnull)sender;
- (void)onSuccessSendOpportunity;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect18DescriptionPackage")
@interface DescriptionPackage : NSObject
@property (nonatomic, copy) NSString * _Nullable descriptionP;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable iconDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;

SWIFT_CLASS("_TtC8prospect28DescriptionPackageDataSource")
@interface DescriptionPackageDataSource : NSObject <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) UITableView * _Nullable tableView;
@property (nonatomic, copy) NSArray<DescriptionPackage *> * _Nonnull descriptionArray;
- (nonnull instancetype)initWithTableView:(UITableView * _Nonnull)tableView OBJC_DESIGNATED_INITIALIZER;
- (void)updateWithColeccionInfo:(NSArray<DescriptionPackage *> * _Nonnull)coleccionInfo;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didDeselectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect31DescriptionPackageTableViewCell")
@interface DescriptionPackageTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class PredictionAddress;

SWIFT_CLASS("_TtC8prospect17DirectionResponse")
@interface DirectionResponse : NSObject
@property (nonatomic, copy) NSArray<PredictionAddress *> * _Nonnull predictionData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect21FamilyPackageResponse")
@interface FamilyPackageResponse : BaseResponse
@property (nonatomic, copy) NSArray<Plans *> * _Nonnull plans;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class IDPlan;

SWIFT_CLASS("_TtC8prospect23FamilyPackagesPresenter")
@interface FamilyPackagesPresenter : BaseEstrategiaPresenter
@property (nonatomic, strong) ArrFamily * _Null_unspecified mArrFamily;
@property (nonatomic, copy) NSArray<IDPlan *> * _Nonnull midPlans;
- (void)viewDidLoad;
- (void)loadFamilyPackage;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
- (void)onSuccessFamilyPackageWithRequestUrl:(NSString * _Nonnull)requestUrl familyPackageResponse:(FamilyPackageResponse * _Nonnull)familyPackageResponse;
@end


SWIFT_CLASS("_TtC8prospect11Feasibility")
@interface Feasibility : NSObject
@property (nonatomic, copy) NSString * _Nonnull feasible;
@property (nonatomic, copy) NSString * _Nonnull region;
@property (nonatomic, copy) NSString * _Nonnull regionId;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull district;
@property (nonatomic, copy) NSString * _Nonnull cluster;
@property (nonatomic, copy) NSString * _Nonnull zoneValue;
@property (nonatomic, copy) NSString * _Nonnull judgment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect11FileRequest")
@interface FileRequest : NSObject
@property (nonatomic, strong) LoginRequest * _Nullable login;
@property (nonatomic, strong) AttachmentRequest * _Nullable attachmentRequest;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect13FilesResponse")
@interface FilesResponse : NSObject
@property (nonatomic, strong) ResultBean * _Nullable result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect17GeocoderPresenter")
@interface GeocoderPresenter : BaseEstrategiaPresenter
- (void)getAddressForLatLngWithLatitude:(NSString * _Nonnull)latitude longitude:(NSString * _Nonnull)longitude;
- (void)loadAddressFromZipCodeWithZipCode:(NSString * _Nonnull)zipCode;
- (void)successLoadAddressWithRequestUrl:(NSString * _Nonnull)requestUrl addressCpResponse:(AddressCpResponse * _Nonnull)addressCpResponse;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
@end

@class Location;

SWIFT_CLASS("_TtC8prospect8Geometry")
@interface Geometry : NSObject
@property (nonatomic, strong) Location * _Nullable location;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ResultLocation;

SWIFT_CLASS("_TtC8prospect16GeometryResponse")
@interface GeometryResponse : NSObject
@property (nonatomic, strong) ResultLocation * _Nullable result;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect6IDPlan")
@interface IDPlan : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithIdPlan:(NSString * _Nonnull)idPlan OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect13IconTextField")
@interface IconTextField : UITextField <UITextFieldDelegate>
@property (nonatomic) NSInteger maxCharacters;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable elements;
@property (nonatomic) NSInteger indexElementPicker;
@property (nonatomic) BOOL isEnablePicker;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)setDatePicker;
- (void)setCreditCardDatePicker;
- (void)setTextPickerWithElements:(NSArray<NSString *> * _Nonnull)elements;
- (void)tapBlurButton:(UITapGestureRecognizer * _Nonnull)sender;
- (void)tapDateBlurButton:(UITapGestureRecognizer * _Nonnull)sender;
- (void)tapCreditCardDateBlurButton:(UITapGestureRecognizer * _Nonnull)sender;
- (void)showActionDatePickerWithDate:(NSString * _Nullable)date;
- (void)showActionCreditCardDatePickerWithDate:(NSString * _Nullable)date;
- (void)showActionPicker;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect33ItemAddCardCollectionReusableView")
@interface ItemAddCardCollectionReusableView : UICollectionReusableView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect33ItemPackageCollectionReusableView")
@interface ItemPackageCollectionReusableView : UICollectionReusableView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect21ItemPagoTableViewCell")
@interface ItemPagoTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect34ItemTypeCardCollectionReusableView")
@interface ItemTypeCardCollectionReusableView : UICollectionReusableView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect8Location")
@interface Location : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocationManager;
@class CLLocation;
@class ValidateCoverageResponse;

SWIFT_CLASS("_TtC8prospect26MapLocationSearchPresenter")
@interface MapLocationSearchPresenter : BaseEstrategiaPresenter <CLLocationManagerDelegate>
- (void)viewDidLoad;
- (void)requestLocation;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManagerWithManager:(CLLocationManager * _Null_unspecified)manager didUpdateLocations:(NSArray * _Null_unspecified)locations;
- (void)successLoadCoverageValidateWithRequestUrl:(NSString * _Nonnull)requestUrl validateCoverageResponse:(ValidateCoverageResponse * _Nonnull)validateCoverageResponse;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
- (void)onErrorLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl messageError:(NSString * _Nonnull)messageError;
@end

@class MetodoPagoBean;

SWIFT_CLASS("_TtC8prospect22MethodPaymentPresenter")
@interface MethodPaymentPresenter : BaseEstrategiaPresenter
- (void)saveMethodPaymentWithMetodoPagoBean:(MetodoPagoBean * _Nonnull)metodoPagoBean;
@end




SWIFT_CLASS("_TtC8prospect19NoCoveragePresenter")
@interface NoCoveragePresenter : BaseEstrategiaPresenter
- (void)NoCoverageWithName:(NSString * _Nonnull)name email:(NSString * _Nonnull)email phone:(NSString * _Nonnull)phone zipCode:(NSString * _Nonnull)zipCode colony:(NSString * _Nonnull)colony;
- (void)onRequestWs;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
- (void)onSuccessSendNoCoverage;
@end

@class ClientData;

SWIFT_CLASS("_TtC8prospect17NoCoverageRequest")
@interface NoCoverageRequest : BaseRequest
@property (nonatomic, strong) ClientData * _Nullable clientData;
- (nonnull instancetype)initWithClientData:(ClientData * _Nonnull)clientData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect19OpportunityResponse")
@interface OpportunityResponse : BaseResponse
@property (nonatomic, copy) NSString * _Nullable CuentaId;
@property (nonatomic, copy) NSString * _Nullable OportunidadId;
@property (nonatomic, copy) NSString * _Nullable SitioId;
@property (nonatomic, copy) NSString * _Nullable CotizacionId;
@property (nonatomic, copy) NSString * _Nullable CuentaFacturaId;
@property (nonatomic, copy) NSString * _Nullable CuentaBRM;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect21PackageDoblePhoneCell")
@interface PackageDoblePhoneCell : BaseTableViewCell
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (void)pupulateSelectedWithObject:(NSObject * _Nonnull)object;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect18PackageDobleTVCell")
@interface PackageDobleTVCell : BaseTableViewCell
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (void)pupulateSelectedWithObject:(NSObject * _Nonnull)object;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect17PackageTripleCell")
@interface PackageTripleCell : BaseTableViewCell
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (void)pupulateSelectedWithObject:(NSObject * _Nonnull)object;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect24PackageTypeTableViewCell")
@interface PackageTypeTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ProductMasterPlanesResponse;

SWIFT_CLASS("_TtC8prospect21PackagesTypePresenter")
@interface PackagesTypePresenter : BaseEstrategiaPresenter
@property (nonatomic, copy) NSString * _Nonnull mSelectedType;
- (void)loadHomePackages;
- (void)loadBusinessPackages;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
- (void)onSuccessPMPlanesWithProducMaster:(ProductMasterPlanesResponse * _Nonnull)producMaster;
@end


SWIFT_CLASS("_TtC8prospect26PackagesTypeViewController")
@interface PackagesTypeViewController : BaseViewController <UITableViewDelegate>
@property (nonatomic, copy) NSArray<ArrFamily *> * _Null_unspecified mArrFamily;
@property (nonatomic, strong) ArrFamily * _Nullable mArrFamilyBussiness;
@property (nonatomic, strong) PackagesTypePresenter * _Nullable mPackagesTypePresenter;
@property (nonatomic, copy) NSString * _Nullable mTypePlanSelected;
- (void)viewDidLoad;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (IBAction)mBusinessButton:(id _Nonnull)sender;
- (IBAction)mHomeButton:(id _Nonnull)sender;
- (IBAction)nextButton:(id _Nonnull)sender;
- (void)onItemClickWithItem:(NSArray<ArrPlan *> * _Nonnull)item;
- (void)onSuccessPMPlanesWithArrFamily:(NSArray<ArrFamily *> * _Nonnull)arrFamily;
- (void)onTableViewCellClickWithItem:(NSObject * _Nonnull)item cell:(UITableViewCell * _Nonnull)cell;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect22PackagesViewController")
@interface PackagesViewController : BaseViewController
@property (nonatomic, copy) NSArray<DescriptionPackage *> * _Nonnull descriptionArray;
@property (nonatomic, strong) DescriptionPackageDataSource * _Nullable descriptionPDataSoure;
@property (nonatomic, strong) CarruselDataSource * _Nullable mCarruselDataSource;
@property (nonatomic, strong) FamilyPackagesPresenter * _Nullable mFamilyPackagePresenter;
@property (nonatomic, copy) NSArray<Plans *> * _Nonnull mArrayFamily;
- (void)viewDidLoad;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (void)didReceiveMemoryWarning;
- (void)onSuccessFamilyPackageWithFamilyPackageResponse:(NSArray<Plans *> * _Nonnull)familyPackageResponse;
- (void)onItemClickWithPlanSelected:(Plans * _Nonnull)planSelected;
- (void)onChangeItemWithPlanDetail:(NSString * _Nonnull)planDetail planName:(NSString * _Nonnull)planName;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect27PaymentMethodViewController")
@interface PaymentMethodViewController : BaseViewController
@property (nonatomic, strong) MethodPaymentPresenter * _Null_unspecified mPaymentMethodPresenter;
- (void)viewDidLoad;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (void)loadMethodCashPay;
- (void)loadMethodCardPay;
- (void)onSuccessLoadInfoPaymentWithMetodoPagoBean:(MetodoPagoBean * _Nonnull)metodoPagoBean;
- (IBAction)mTypeMethodSegmentControl:(id _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ContactoBean;
@class DatosAdicionalesBean;

SWIFT_CLASS("_TtC8prospect19PersonDataPresenter")
@interface PersonDataPresenter : BaseEstrategiaPresenter
- (void)saveContactoBeanWithContactoBean:(ContactoBean * _Nonnull)contactoBean infoAdicionalBean:(DatosAdicionalesBean * _Nonnull)infoAdicionalBean;
@end

@class UISegmentedControl;

SWIFT_CLASS("_TtC8prospect24PersonDataViewController")
@interface PersonDataViewController : BaseEstrategiaViewController
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull mIdentificationTypes;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull mContactTye;
@property (nonatomic, strong) FormValidator * _Null_unspecified mFormValidator;
@property (nonatomic, strong) PersonDataPresenter * _Null_unspecified mPersonDataPresenter;
- (void)viewDidLoad;
- (void)loadContactInfo;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (void)didReceiveMemoryWarning;
- (IBAction)mPersonTypeSegmentedControl:(UISegmentedControl * _Nonnull)sender;
- (IBAction)onNextButtonClick:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect18PlainDetailRequest")
@interface PlainDetailRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nullable idPlan;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithIdPlan:(NSString * _Nonnull)idPlan OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect18PlanDetailResponse")
@interface PlanDetailResponse : BaseResponse
@property (nonatomic, copy) NSArray<ArrServiciosIncluidos *> * _Nonnull arrServiciosIncluidos;
@property (nonatomic, copy) NSArray<ArrServiciosAdicionales *> * _Nonnull arrServiciosAdicionales;
@property (nonatomic, copy) NSArray<ArrProductosAdicionales *> * _Nonnull arrProductosAdicionales;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect5Plans")
@interface Plans : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect15PlansDataSource")
@interface PlansDataSource : NSObject <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) UITableView * _Nullable tableView;
@property (nonatomic, copy) NSArray<ArrFamily *> * _Nonnull arrFamily;
@property (nonatomic, strong) PackageTypeTableViewCell * _Nullable cell;
- (void)updateWithArrayFamily:(ProductMasterPlanesResponse * _Nonnull)arrayFamily;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class Terms;

SWIFT_CLASS("_TtC8prospect17PredictionAddress")
@interface PredictionAddress : NSObject
@property (nonatomic, copy) NSString * _Nullable description_;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable place_id;
@property (nonatomic, copy) NSArray<Terms *> * _Nonnull terms;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC8prospect26PredictionAddressPresenter")
@interface PredictionAddressPresenter : BaseEstrategiaPresenter
- (void)getPredictionAddressWithKeyword:(NSString * _Nonnull)keyword;
- (void)getLatLonWithPlaceId:(NSString * _Nonnull)placeId;
@end


SWIFT_CLASS("_TtC8prospect27ProductMasterPlanesResponse")
@interface ProductMasterPlanesResponse : BaseResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;

SWIFT_CLASS("_TtC8prospect13ProspectRoute")
@interface ProspectRoute : NSObject
+ (void)prospectWithViewController:(UIViewController * _Nonnull)viewController services:(NSString * _Nonnull)services Places:(NSString * _Nonnull)Places;
+ (void)instanceAppDelegatePros;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AddressComponent;

SWIFT_CLASS("_TtC8prospect14ResultLocation")
@interface ResultLocation : NSObject
@property (nonatomic, strong) Geometry * _Nullable geometry;
@property (nonatomic, copy) NSArray<AddressComponent *> * _Nonnull formattedAddress;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect8Security")
@interface Security : NSObject
+ (NSString * _Nonnull)cryptWithText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect24SendOpportunityPresenter")
@interface SendOpportunityPresenter : BaseEstrategiaPresenter
- (void)sendOpportunity;
- (void)successAddOpportunityWithRequestUrl:(NSString * _Nonnull)requestUrl opportunityResponse:(OpportunityResponse * _Nonnull)opportunityResponse;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
- (ContactoBean * _Nonnull)generateContactoWithContactoBean:(ContactoBean * _Nonnull)contactoBean SWIFT_WARN_UNUSED_RESULT;
- (MetodoPagoBean * _Nonnull)generateMetodoPagoWithMetodoPagoBean:(MetodoPagoBean * _Nonnull)metodoPagoBean SWIFT_WARN_UNUSED_RESULT;
@end

@class AddOn;

SWIFT_CLASS("_TtC8prospect22ServiceAddOnDataSource")
@interface ServiceAddOnDataSource : NSObject <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) UITableView * _Nullable tableView;
@property (nonatomic, copy) NSArray<AddOn *> * _Nonnull addOnArray;
- (nonnull instancetype)initWithTableView:(UITableView * _Nonnull)tableView OBJC_DESIGNATED_INITIALIZER;
- (void)updateWithColeccionInfo:(NSArray<AddOn *> * _Nonnull)coleccionInfo;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didDeselectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect6Suburb")
@interface Suburb : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable suburb;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable cluster;
@property (nonatomic, copy) NSString * _Nullable delegation;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable stateEnId;
@property (nonatomic, copy) NSString * _Nullable stateTpId;
@property (nonatomic, copy) NSString * _Nullable delegationEnId;
@property (nonatomic, copy) NSString * _Nullable delegationTpId;
@property (nonatomic, copy) NSString * _Nullable idSource;
@property (nonatomic, copy) NSString * _Nullable idPopulationEn;
@property (nonatomic, copy) NSString * _Nullable idPopulationTP;
@property (nonatomic, copy) NSString * _Nullable idRegionEn;
@property (nonatomic, copy) NSString * _Nullable idRegionTP;
@property (nonatomic, copy) NSString * _Nullable limit;
@property (nonatomic, copy) NSString * _Nullable limit1;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect13SyncImageCell")
@interface SyncImageCell : BaseTableViewCell
- (void)pupulateWithObject:(NSObject * _Nonnull)object;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect24SyncImagesViewController")
@interface SyncImagesViewController : BaseEstrategiaViewController
- (void)viewDidLoad;
- (void)onSyncStatusChange;
- (void)onSyncError;
- (void)onSyncFinish;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC8prospect18TakePhotoPresenter")
@interface TakePhotoPresenter : BaseEstrategiaPresenter
- (UIImage * _Nonnull)imageWithSizeWithImage:(UIImage * _Nonnull)image size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8prospect23TakePhotoViewController")
@interface TakePhotoViewController : BaseEstrategiaViewController
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_PHOTO_FRONT_SIDE;)
+ (NSString * _Nonnull)REQUEST_CODE_PHOTO_FRONT_SIDE SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_PHOTO_FRONT_SIDE:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_PHOTO_BEHIN_SIDE;)
+ (NSString * _Nonnull)REQUEST_CODE_PHOTO_BEHIN_SIDE SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_PHOTO_BEHIN_SIDE:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull REQUEST_CODE_PHOTO_ADDRESS_VOUCHER;)
+ (NSString * _Nonnull)REQUEST_CODE_PHOTO_ADDRESS_VOUCHER SWIFT_WARN_UNUSED_RESULT;
+ (void)setREQUEST_CODE_PHOTO_ADDRESS_VOUCHER:(NSString * _Nonnull)value;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull mIdentificationTypes;
@property (nonatomic, strong) TakePhotoPresenter * _Null_unspecified mTakePhotoPresenter;
@property (nonatomic, strong) FormValidator * _Null_unspecified mFormValidator;
@property (nonatomic) BOOL isSelectedVoucherAddress;
@property (nonatomic) BOOL isPhotoOne;
@property (nonatomic) BOOL isPhotoTwo;
@property (nonatomic) BOOL isPhotoThree;
- (void)viewDidLoad;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (IBAction)onVoucherCheckButtonClick:(id _Nonnull)sender;
- (IBAction)onSaveClick:(id _Nonnull)sender;
- (void)SaveImages;
- (IBAction)mIdFrontSideButton:(id _Nonnull)sender;
- (IBAction)mIdBehindSideButton:(id _Nonnull)sender;
- (IBAction)mAddressVoucherButton:(id _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect28TrackingTicketViewController")
@interface TrackingTicketViewController : BaseEstrategiaViewController
- (void)viewDidLoad;
- (void)clearData;
- (void)didReceiveMemoryWarning;
- (IBAction)mSaveButton:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8prospect23ValidateCoverageRequest")
@interface ValidateCoverageRequest : BaseRequest
@property (nonatomic, copy) NSString * _Nullable latitude;
@property (nonatomic, copy) NSString * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable clientType;
- (nonnull instancetype)initWithLatitude:(NSString * _Nonnull)latitude longitude:(NSString * _Nonnull)longitude OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8prospect24ValidateCoverageResponse")
@interface ValidateCoverageResponse : BaseResponse
@property (nonatomic, strong) Feasibility * _Null_unspecified feasibility;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
