// Generated by Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import RealmSwift;
@import UIKit;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("BaseClases")

SWIFT_CLASS("_TtC10BaseClases5AddOn")
@interface AddOn : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18AdditionalServices")
@interface AdditionalServices : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases6Addons")
@interface Addons : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases16AddressComponent")
@interface AddressComponent : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13ApiDefinition")
@interface ApiDefinition : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases7ArrPlan")
@interface ArrPlan : NSObject
@property (nonatomic, copy) NSString * _Nonnull planId;
@property (nonatomic, copy) NSString * _Nonnull planName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RLMRealm;
@class RLMObjectSchema;
@class RLMSchema;

SWIFT_CLASS("_TtC10BaseClases11ArrPlanBean")
@interface ArrPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nullable id_plan;
@property (nonatomic, copy) NSString * _Nullable name_plan;
@property (nonatomic, copy) NSString * _Nullable type_coverage;
@property (nonatomic, copy) NSString * _Nullable type_provisioning;
@property (nonatomic, copy) NSString * _Nullable type_billing;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic, copy) NSString * _Nullable allow_discount_rent;
@property (nonatomic, copy) NSString * _Nullable allow_discount_unique_charge;
@property (nonatomic, copy) NSString * _Nullable subtype_oportunity;
@property (nonatomic, copy) NSString * _Nullable tm_code_arrear;
@property (nonatomic, copy) NSString * _Nullable tm_code_fwd;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases23ArrProductosAdicionales")
@interface ArrProductosAdicionales : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull esProntoPago;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull agrupacionAddon;
@property (nonatomic, copy) NSString * _Nonnull cantidadDN;
@property (nonatomic, copy) NSString * _Nonnull cantidadTroncal;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull esAutomaticoCiudad;
@property (nonatomic, copy) NSString * _Nonnull esCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull estatus;
@property (nonatomic, copy) NSString * _Nonnull esVisible;
@property (nonatomic, copy) NSString * _Nonnull idBrmArrear;
@property (nonatomic, copy) NSString * _Nonnull idBrmCU;
@property (nonatomic, copy) NSString * _Nonnull idBrmForward;
@property (nonatomic, copy) NSString * _Nonnull iEPS;
@property (nonatomic, copy) NSString * _Nonnull iVA;
@property (nonatomic, copy) NSString * _Nonnull maximoAgregar;
@property (nonatomic, copy) NSString * _Nonnull nombreEditable;
@property (nonatomic, copy) NSString * _Nonnull planDescuentoId;
@property (nonatomic, copy) NSString * _Nonnull plazo;
@property (nonatomic, copy) NSString * _Nonnull precioBase;
@property (nonatomic, copy) NSString * _Nonnull precioEditable;
@property (nonatomic, copy) NSString * _Nonnull precioProntoPago;
@property (nonatomic, copy) NSString * _Nonnull productoPadre;
@property (nonatomic, copy) NSString * _Nonnull tipoProducto;
@property (nonatomic, copy) NSString * _Nonnull tipoProductoTexto;
@property (nonatomic, copy) NSString * _Nonnull idProducto;
@property (nonatomic, copy) NSString * _Nonnull nameProducto;
@property (nonatomic, copy) NSString * _Nonnull productoId;
@property (nonatomic, copy) NSString * _Nonnull ciudad;
@property (nonatomic, copy) NSString * _Nonnull velocidadSubida;
@property (nonatomic, copy) NSString * _Nonnull velocidadBajada;
@property (nonatomic, copy) NSString * _Nonnull tieneIPDinamica;
@property (nonatomic, copy) NSString * _Nonnull tieneIPFija;
@property (nonatomic, copy) NSString * _Nonnull tieneSTBAdicional;
@property (nonatomic, copy) NSString * _Nonnull esCCTV;
@property (nonatomic, copy) NSString * _Nonnull esWiFi;
@property (nonatomic, copy) NSString * _Nonnull cantidad;
@property (nonatomic, copy) NSString * _Nonnull estatusProducto;
@property (nonatomic, copy) NSString * _Nonnull fechaInicio;
@property (nonatomic, copy) NSString * _Nonnull fechaFin;
@property (nonatomic, copy) NSString * _Nonnull comentarioProducto;
@property (nonatomic, copy) NSString * _Nonnull priceApp;
@property (nonatomic, copy) NSString * _Nonnull image;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases27ArrProductosConvivenciaBean")
@interface ArrProductosConvivenciaBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Id;
@property (nonatomic, copy) NSString * _Nonnull Name;
@property (nonatomic, copy) NSString * _Nonnull Comentario;
@property (nonatomic, copy) NSString * _Nonnull Estatus;
@property (nonatomic, copy) NSString * _Nonnull ProductoId;
@property (nonatomic, copy) NSString * _Nonnull ProductoExcIncId;
@property (nonatomic, copy) NSString * _Nonnull Tipo;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20ArrProductosIncluido")
@interface ArrProductosIncluido : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull agrupacionAddon;
@property (nonatomic, copy) NSString * _Nonnull cantidadDN;
@property (nonatomic, copy) NSString * _Nonnull cantidadTroncal;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull esAutomaticoCiudad;
@property (nonatomic, copy) NSString * _Nonnull esCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull estatus;
@property (nonatomic, copy) NSString * _Nonnull esVisible;
@property (nonatomic, copy) NSString * _Nonnull idBrmArrear;
@property (nonatomic, copy) NSString * _Nonnull idBrmCU;
@property (nonatomic, copy) NSString * _Nonnull idBrmForward;
@property (nonatomic, copy) NSString * _Nonnull iEPS;
@property (nonatomic, copy) NSString * _Nonnull iVA;
@property (nonatomic, copy) NSString * _Nonnull maximoAgregar;
@property (nonatomic, copy) NSString * _Nonnull nombreEditable;
@property (nonatomic, copy) NSString * _Nonnull planDescuentoId;
@property (nonatomic, copy) NSString * _Nonnull plazo;
@property (nonatomic, copy) NSString * _Nonnull precioBase;
@property (nonatomic, copy) NSString * _Nonnull precioEditable;
@property (nonatomic, copy) NSString * _Nonnull precioProntoPago;
@property (nonatomic, copy) NSString * _Nonnull productoPadre;
@property (nonatomic, copy) NSString * _Nonnull tipoProducto;
@property (nonatomic, copy) NSString * _Nonnull idProducto;
@property (nonatomic, copy) NSString * _Nonnull nameProducto;
@property (nonatomic, copy) NSString * _Nonnull productoId;
@property (nonatomic, copy) NSString * _Nonnull ciudad;
@property (nonatomic, copy) NSString * _Nonnull velocidadSubida;
@property (nonatomic, copy) NSString * _Nonnull velocidadBajada;
@property (nonatomic, copy) NSString * _Nonnull tieneIPDinamica;
@property (nonatomic, copy) NSString * _Nonnull tieneIPFija;
@property (nonatomic, copy) NSString * _Nonnull tieneSTBAdicional;
@property (nonatomic, copy) NSString * _Nonnull esCCTV;
@property (nonatomic, copy) NSString * _Nonnull esWiFi;
@property (nonatomic, copy) NSString * _Nonnull cantidad;
@property (nonatomic, copy) NSString * _Nonnull estatusProducto;
@property (nonatomic, copy) NSString * _Nonnull fechaInicio;
@property (nonatomic, copy) NSString * _Nonnull fechaFin;
@property (nonatomic, copy) NSString * _Nonnull comentarioProducto;
@property (nonatomic, copy) NSString * _Nonnull esProntoPago;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13BasePresenter")
@interface BasePresenter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases23BaseEstrategiaPresenter")
@interface BaseEstrategiaPresenter : BasePresenter
@end

@class UITextField;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC10BaseClases18BaseViewController")
@interface BaseViewController : UIViewController <UITextFieldDelegate>
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)hideKeyboard;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases28BaseEstrategiaViewController")
@interface BaseEstrategiaViewController : BaseViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases28BaseNavigationViewController")
@interface BaseNavigationViewController : UINavigationController
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10BaseClases16BaseRealmRequest")
@interface BaseRealmRequest : RealmSwiftObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11BaseRequest")
@interface BaseRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12BaseResponse")
@interface BaseResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases24BaseTabBarViewController")
@interface BaseTabBarViewController : UITabBarController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10BaseClases11BillingInfo")
@interface BillingInfo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases4Card")
@interface Card : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases9CardsEnum")
@interface CardsEnum : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10ClientData")
@interface ClientData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10ColorUtils")
@interface ColorUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12ContactoBean")
@interface ContactoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull TipoPersona;
@property (nonatomic, copy) NSString * _Nonnull Nombre;
@property (nonatomic, copy) NSString * _Nonnull ApellidoPaterno;
@property (nonatomic, copy) NSString * _Nonnull ApellidoMaterno;
@property (nonatomic, copy) NSString * _Nonnull Telefono;
@property (nonatomic, copy) NSString * _Nonnull OtroTelefono;
@property (nonatomic, copy) NSString * _Nonnull Celular;
@property (nonatomic, copy) NSString * _Nonnull CorreoElectronico;
@property (nonatomic, copy) NSString * _Nonnull OtroCorreoElectronico;
@property (nonatomic, copy) NSString * _Nonnull RFC;
@property (nonatomic, copy) NSString * _Nonnull RazonSocial;
@property (nonatomic, copy) NSString * _Nonnull MedioContacto;
@property (nonatomic, copy) NSString * _Nonnull FechaNacimiento;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20CotPlanPromocionBean")
@interface CotPlanPromocionBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases19CotPlanServicioBean")
@interface CotPlanServicioBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull CategoriaServicio;
@property (nonatomic, copy) NSString * _Nonnull DN_Principal;
@property (nonatomic, copy) NSString * _Nonnull DNsActivados;
@property (nonatomic, copy) NSString * _Nonnull DP_PlanServicio;
@property (nonatomic, copy) NSString * _Nonnull EsServicioAdicional;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacion;
@property (nonatomic, copy) NSString * _Nonnull IdExterno_ws;
@property (nonatomic, copy) NSString * _Nonnull IpFijasActivadas;
@property (nonatomic, copy) NSString * _Nonnull NombrePlan;
@property (nonatomic, copy) NSString * _Nonnull NombreServicio;
@property (nonatomic, copy) NSString * _Nonnull SRV_Mode;
@property (nonatomic, copy) NSString * _Nonnull Tipo;
@property (nonatomic, copy) NSString * _Nonnull DP_PromocionPlan;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases23CotServicioProductoBean")
@interface CotServicioProductoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Cantidad;
@property (nonatomic, copy) NSString * _Nonnull CantidadDN;
@property (nonatomic, copy) NSString * _Nonnull CantidadTroncal;
@property (nonatomic, copy) NSString * _Nonnull Descuento;
@property (nonatomic, copy) NSString * _Nonnull DP_Producto;
@property (nonatomic, copy) NSString * _Nonnull DP_PromocionServicioProducto;
@property (nonatomic, copy) NSString * _Nonnull DP_ServicioProducto;
@property (nonatomic, copy) NSString * _Nonnull EsCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull EsDescuento;
@property (nonatomic, copy) NSString * _Nonnull EsProductoAdicional;
@property (nonatomic, copy) NSString * _Nonnull EsProntoPago;
@property (nonatomic, copy) NSString * _Nonnull EsServicioRepetido;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacion;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacionDescripcion;
@property (nonatomic, copy) NSString * _Nonnull FechaFin;
@property (nonatomic, copy) NSString * _Nonnull FechaInicio;
@property (nonatomic, copy) NSString * _Nonnull GeneraDNs;
@property (nonatomic, copy) NSString * _Nonnull Impuesto2;
@property (nonatomic, copy) NSString * _Nonnull Impuesto1;
@property (nonatomic, copy) NSString * _Nonnull MontoImpuestos;
@property (nonatomic, copy) NSString * _Nonnull NombreProducto;
@property (nonatomic, copy) NSString * _Nonnull PrecioUnitario;
@property (nonatomic, copy) NSString * _Nonnull PrecioUnitario_ProntoPago;
@property (nonatomic, copy) NSString * _Nonnull PrecioUnitarioBase;
@property (nonatomic, copy) NSString * _Nonnull ProductoPadre;
@property (nonatomic, copy) NSString * _Nonnull TieneIPDinamica;
@property (nonatomic, copy) NSString * _Nonnull TieneIPFija;
@property (nonatomic, copy) NSString * _Nonnull TipoIp;
@property (nonatomic, copy) NSString * _Nonnull TipoProducto;
@property (nonatomic, copy) NSString * _Nonnull VelocidadBajada;
@property (nonatomic, copy) NSString * _Nonnull VelocidadSubida;
@property (nonatomic, copy) NSString * _Nonnull DP_PromocionPlan;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases16CotSitioPlanBean")
@interface CotSitioPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull DescuentoCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull DescuentoRenta;
@property (nonatomic, copy) NSString * _Nonnull DN_Principal;
@property (nonatomic, copy) NSString * _Nonnull DP_Plan;
@property (nonatomic, copy) NSString * _Nonnull DP_DescuentoLimiteCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull DP_DescuentoLimiteRenta;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacion;
@property (nonatomic, copy) NSString * _Nonnull NombrePlan;
@property (nonatomic, copy) NSString * _Nonnull PrecioProntoPago;
@property (nonatomic, copy) NSString * _Nonnull Ticket;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases15CreditCardUtils")
@interface CreditCardUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases19DPPromocionPlanBean")
@interface DPPromocionPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Id;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18DPServicioProducto")
@interface DPServicioProducto : RealmSwiftObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11DataManager")
@interface DataManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases9DateUtils")
@interface DateUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20DatosAdicionalesBean")
@interface DatosAdicionalesBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull TipoIdentificacion;
@property (nonatomic, copy) NSString * _Nonnull IdentificacionOficial;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11DeviceUtils")
@interface DeviceUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13DireccionBean")
@interface DireccionBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull zipCode;
@property (nonatomic, copy) NSString * _Nonnull colony;
@property (nonatomic, copy) NSString * _Nonnull delegation;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull street;
@property (nonatomic, copy) NSString * _Nonnull noExt;
@property (nonatomic, copy) NSString * _Nonnull noInt;
@property (nonatomic, copy) NSString * _Nonnull betweenStreets;
@property (nonatomic, copy) NSString * _Nonnull ReferenciaUrbana;
@property (nonatomic, copy) NSString * _Nonnull authorizationWhitoutCoverage;
@property (nonatomic, copy) NSString * _Nonnull cluster;
@property (nonatomic, copy) NSString * _Nonnull place;
@property (nonatomic, copy) NSString * _Nonnull district;
@property (nonatomic, copy) NSString * _Nonnull feasibility;
@property (nonatomic, copy) NSString * _Nonnull feasible;
@property (nonatomic, copy) NSString * _Nonnull typeCoverage;
@property (nonatomic, copy) NSString * _Nonnull region;
@property (nonatomic, copy) NSString * _Nonnull idRegion;
@property (nonatomic, copy) NSString * _Nonnull zoneValue;
@property (nonatomic, copy) NSString * _Nonnull latitude;
@property (nonatomic, copy) NSString * _Nonnull longitude;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases24DireccionFacturacionBean")
@interface DireccionFacturacionBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull MismaDireccionInstalacion;
@property (nonatomic, copy) NSString * _Nonnull FolioContrato;
@property (nonatomic, copy) NSString * _Nonnull Calle;
@property (nonatomic, copy) NSString * _Nonnull NumeroExterior;
@property (nonatomic, copy) NSString * _Nonnull NumeroInterior;
@property (nonatomic, copy) NSString * _Nonnull ColoniaCP;
@property (nonatomic, copy) NSString * _Nonnull Colonia;
@property (nonatomic, copy) NSString * _Nonnull DelegacionMunicipio;
@property (nonatomic, copy) NSString * _Nonnull Ciudad;
@property (nonatomic, copy) NSString * _Nonnull Estado;
@property (nonatomic, copy) NSString * _Nonnull CodigoPostal;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18EncryptedLoginBean")
@interface EncryptedLoginBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull user;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull ip;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class MetodoPagoBean;
@class ReferenciasBean;

SWIFT_CLASS("_TtC10BaseClases9FirmaBean")
@interface FirmaBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, strong) DireccionFacturacionBean * _Nullable DireccionFacturacion;
@property (nonatomic, strong) DatosAdicionalesBean * _Nullable DatosAdicionales;
@property (nonatomic, strong) MetodoPagoBean * _Nullable MetodoPago;
@property (nonatomic, strong) ReferenciasBean * _Nullable Referencias;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13FormValidator")
@interface FormValidator : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class ProspectoBean;
@class SaleReleaseBean;

SWIFT_CLASS("_TtC10BaseClases15FormalityEntity")
@interface FormalityEntity : BaseRealmRequest
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, strong) ProspectoBean * _Nullable Prospecto;
@property (nonatomic, strong) SaleReleaseBean * _Nullable saleRelease;
@property (nonatomic, strong) EncryptedLoginBean * _Nullable loginBean;
@property (nonatomic) BOOL isUsedIdAsProof;
@property (nonatomic) double totalPriceList;
@property (nonatomic) double totalPriceSoonPayment;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases6Imagen")
@interface Imagen : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull image;
@property (nonatomic, copy) NSString * _Nonnull thumbnail;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull opportunityId;
@property (nonatomic, copy) NSString * _Nonnull brmAccount;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull syncStatus;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11Information")
@interface Information : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases15LastBillBalance")
@interface LastBillBalance : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12LoginRequest")
@interface LoginRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases14MetodoPagoBean")
@interface MetodoPagoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Metodo;
@property (nonatomic, copy) NSString * _Nonnull TipoTarjeta;
@property (nonatomic, copy) NSString * _Nonnull NombreTitular;
@property (nonatomic, copy) NSString * _Nonnull ApellidoPaternoTitular;
@property (nonatomic, copy) NSString * _Nonnull ApellidoMaternoTitular;
@property (nonatomic, copy) NSString * _Nonnull NumeroTarjeta;
@property (nonatomic, copy) NSString * _Nonnull VencimientoMes;
@property (nonatomic, copy) NSString * _Nonnull VencimientoAnio;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases8NameData")
@interface NameData : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nullable name;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases7NewCard")
@interface NewCard : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases12PackagesType")
@interface PackagesType : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases19PopUpViewController")
@interface PopUpViewController : BaseViewController <UIGestureRecognizerDelegate>
- (void)viewDidLoad;
- (void)keyboardWillShow:(NSNotification * _Nonnull)sender;
- (void)keyboardWillHide:(NSNotification * _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13PropuestaBean")
@interface PropuestaBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Oferta;
@property (nonatomic, copy) NSString * _Nonnull TipoPago;
@property (nonatomic, strong) CotSitioPlanBean * _Nullable Cot_SitioPlan;
@property (nonatomic, strong) CotPlanPromocionBean * _Nullable Cot_PlanPromocion;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class VendedorBean;

SWIFT_CLASS("_TtC10BaseClases13ProspectoBean")
@interface ProspectoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull PlazoContrato;
@property (nonatomic, copy) NSString * _Nonnull CuentaBRM;
@property (nonatomic, copy) NSString * _Nonnull IdOportunidad;
@property (nonatomic, copy) NSString * _Nonnull IdCuenta;
@property (nonatomic, copy) NSString * _Nonnull IdCuentaFactura;
@property (nonatomic, copy) NSString * _Nonnull IdContacto;
@property (nonatomic, copy) NSString * _Nonnull IdCotizacion;
@property (nonatomic, copy) NSString * _Nonnull IdSitio;
@property (nonatomic, strong) VendedorBean * _Nullable Vendedor;
@property (nonatomic, strong) DireccionBean * _Nullable Direccion;
@property (nonatomic, strong) ContactoBean * _Nullable Contacto;
@property (nonatomic, strong) PropuestaBean * _Nullable Propuesta;
@property (nonatomic, strong) FirmaBean * _Nullable Firma;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases15ReferenciasBean")
@interface ReferenciasBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12ReferidoBean")
@interface ReferidoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Nombre;
@property (nonatomic, copy) NSString * _Nonnull ApellidoPaterno;
@property (nonatomic, copy) NSString * _Nonnull ApellidoMaterno;
@property (nonatomic, copy) NSString * _Nonnull Parentesco;
@property (nonatomic, copy) NSString * _Nonnull Telefono;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases8Response")
@interface Response : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20RestFaultElementBean")
@interface RestFaultElementBean : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases6Result")
@interface Result : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10ResultBean")
@interface ResultBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull result;
@property (nonatomic, copy) NSString * _Nonnull idResult;
@property (nonatomic, copy) NSString * _Nonnull descript;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11ResultLogin")
@interface ResultLogin : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TipoPlanBean;

SWIFT_CLASS("_TtC10BaseClases15SaleReleaseBean")
@interface SaleReleaseBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, strong) TipoPlanBean * _Nullable typePlain;
@property (nonatomic, strong) ArrPlanBean * _Nullable plainBean;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

SWIFT_CLASS("_TtC10BaseClases9Validator")
@interface Validator : NSObject
@property (nonatomic, strong) UIView * _Null_unspecified view;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases25SegmentedControlValidator")
@interface SegmentedControlValidator : Validator
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases10Statements")
@interface Statements : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13StringDialogs")
@interface StringDialogs : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10SyncStatus")
@interface SyncStatus : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases5Terms")
@interface Terms : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18TextFieldValidator")
@interface TextFieldValidator : Validator
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases12TipoPlanBean")
@interface TipoPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nullable tipo;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC10BaseClases4User")
@interface User : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull accountNumber;
+ (NSString * _Nonnull)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10UserPassIp")
@interface UserPassIp : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC10BaseClases12VendedorBean")
@interface VendedorBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull IdEmpleado;
@property (nonatomic, copy) NSString * _Nonnull Canal;
@property (nonatomic, copy) NSString * _Nonnull SubCanal;
@property (nonatomic, copy) NSString * _Nonnull FolioContrato;
@property (nonatomic, copy) NSString * _Nonnull IdDispositivo;
@property (nonatomic, copy) NSString * _Nonnull IdDistrital;
@property (nonatomic, copy) NSString * _Nonnull IdEmpleadoDistrital;
@property (nonatomic, copy) NSString * _Nonnull OrigenApp;
@property (nonatomic, copy) NSString * _Nonnull EsComisionable;
@property (nonatomic, copy) NSString * _Nonnull IMEI;
@property (nonatomic, copy) NSString * _Nonnull ModeloCelular;
@property (nonatomic, copy) NSString * _Nonnull EmpleadoDistribuidor;
@property (nonatomic, copy) NSString * _Nonnull UsuarioLogueado;
@property (nonatomic, copy) NSString * _Nonnull aprobarVentaExpress;
@property (nonatomic, copy) NSString * _Nonnull ventaExpress;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18ViewGroupValidator")
@interface ViewGroupValidator : Validator
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases9ViewUtils")
@interface ViewUtils : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
