// Generated by Apple Swift version 4.0.3 effective-3.2.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import RealmSwift;
@import UIKit;
@import Foundation;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("BaseClases")

SWIFT_CLASS("_TtC10BaseClases5AddOn")
@interface AddOn : NSObject
@property (nonatomic, copy) NSString * _Nullable idAddOn;
@property (nonatomic, copy) NSString * _Nullable nameAddOn;
@property (nonatomic, copy) NSString * _Nullable price;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18AdditionalServices")
@interface AdditionalServices : NSObject
@property (nonatomic, copy) NSString * _Nullable mainImageAdditional;
@property (nonatomic, copy) NSString * _Nullable titleImageAdditional;
@property (nonatomic, copy) NSString * _Nullable legendAdditional;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases6Addons")
@interface Addons : NSObject
@property (nonatomic, copy) NSString * _Nonnull addonName;
@property (nonatomic, copy) NSString * _Nonnull addonPayment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases16AddressComponent")
@interface AddressComponent : NSObject
@property (nonatomic, copy) NSString * _Nullable long_name;
@property (nonatomic, copy) NSString * _Nullable short_name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13ApiDefinition")
@interface ApiDefinition : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull CUSTOM_HEADERS;)
+ (NSDictionary<NSString *, NSString *> * _Nonnull)CUSTOM_HEADERS SWIFT_WARN_UNUSED_RESULT;
/// MAPS
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull GEO_CODING_BASE_URL;)
+ (NSString * _Nonnull)GEO_CODING_BASE_URL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull GEO_CODING_API_KEY;)
+ (NSString * _Nonnull)GEO_CODING_API_KEY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull API_TOTAL;)
+ (NSString * _Nonnull)API_TOTAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_LOGIN;)
+ (NSString * _Nonnull)WS_LOGIN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_REGISTER_USER;)
+ (NSString * _Nonnull)WS_REGISTER_USER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_RECOVERY_PASSWORD;)
+ (NSString * _Nonnull)WS_RECOVERY_PASSWORD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_MY_ACCOUNT;)
+ (NSString * _Nonnull)WS_MY_ACCOUNT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_CONSULT_OT;)
+ (NSString * _Nonnull)WS_CONSULT_OT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_STATEMENTS;)
+ (NSString * _Nonnull)WS_STATEMENTS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_MY_ACCOUNT_BALANCE;)
+ (NSString * _Nonnull)WS_MY_ACCOUNT_BALANCE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_MY_ACCOUNT_CARDS;)
+ (NSString * _Nonnull)WS_MY_ACCOUNT_CARDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_ADD_NEW_CARD;)
+ (NSString * _Nonnull)WS_ADD_NEW_CARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_TRACING_ROUTE;)
+ (NSString * _Nonnull)WS_TRACING_ROUTE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_COVERAGE_VALIDATE;)
+ (NSString * _Nonnull)WS_COVERAGE_VALIDATE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_GET_PLANS;)
+ (NSString * _Nonnull)WS_GET_PLANS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_PLAIN_DETAIL;)
+ (NSString * _Nonnull)WS_PLAIN_DETAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_FAMILY_PACKAGE;)
+ (NSString * _Nonnull)WS_FAMILY_PACKAGE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_CHECK_BILLING_INFORMATION;)
+ (NSString * _Nonnull)WS_CHECK_BILLING_INFORMATION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_PAYMENT_UNIQUE;)
+ (NSString * _Nonnull)WS_PAYMENT_UNIQUE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_PAYMENT_REGISTERED_CARD;)
+ (NSString * _Nonnull)WS_PAYMENT_REGISTERED_CARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_ARRIVAL_TIME;)
+ (NSString * _Nonnull)WS_ARRIVAL_TIME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_NO_COVERAGE;)
+ (NSString * _Nonnull)WS_NO_COVERAGE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_SAVE_ID_DEVICE;)
+ (NSString * _Nonnull)WS_SAVE_ID_DEVICE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_GET_BILLS_BRM;)
+ (NSString * _Nonnull)WS_GET_BILLS_BRM SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_CHECK_BALANCE_BRM;)
+ (NSString * _Nonnull)WS_CHECK_BALANCE_BRM SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull API_QUERY_UPLOAD_DOCUMENT;)
+ (NSString * _Nonnull)API_QUERY_UPLOAD_DOCUMENT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull API_ACD;)
+ (NSString * _Nonnull)API_ACD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull WS_SEND_OPPORTUNITY;)
+ (NSString * _Nonnull)WS_SEND_OPPORTUNITY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull API_CP;)
+ (NSString * _Nonnull)API_CP SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases7ArrPlan")
@interface ArrPlan : NSObject
@property (nonatomic, copy) NSString * _Nonnull planId;
@property (nonatomic, copy) NSString * _Nonnull planName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RLMRealm;
@class RLMObjectSchema;
@class RLMSchema;

SWIFT_CLASS("_TtC10BaseClases11ArrPlanBean")
@interface ArrPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nullable id_plan;
@property (nonatomic, copy) NSString * _Nullable name_plan;
@property (nonatomic, copy) NSString * _Nullable type_coverage;
@property (nonatomic, copy) NSString * _Nullable type_provisioning;
@property (nonatomic, copy) NSString * _Nullable type_billing;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic, copy) NSString * _Nullable allow_discount_rent;
@property (nonatomic, copy) NSString * _Nullable allow_discount_unique_charge;
@property (nonatomic, copy) NSString * _Nullable subtype_oportunity;
@property (nonatomic, copy) NSString * _Nullable tm_code_arrear;
@property (nonatomic, copy) NSString * _Nullable tm_code_fwd;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases23ArrProductosAdicionales")
@interface ArrProductosAdicionales : RealmSwiftObject
- (NSString * _Nonnull)getID SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getAdicionalType SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAdicionalName SWIFT_WARN_UNUSED_RESULT;
- (double)getPrecioBase SWIFT_WARN_UNUSED_RESULT;
- (double)getPrecioProntoPago SWIFT_WARN_UNUSED_RESULT;
- (double)getCantidad SWIFT_WARN_UNUSED_RESULT;
- (double)getIVA SWIFT_WARN_UNUSED_RESULT;
- (double)getIEPS SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull esProntoPago;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull agrupacionAddon;
@property (nonatomic, copy) NSString * _Nonnull cantidadDN;
@property (nonatomic, copy) NSString * _Nonnull cantidadTroncal;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull esAutomaticoCiudad;
@property (nonatomic, copy) NSString * _Nonnull esCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull estatus;
@property (nonatomic, copy) NSString * _Nonnull esVisible;
@property (nonatomic, copy) NSString * _Nonnull idBrmArrear;
@property (nonatomic, copy) NSString * _Nonnull idBrmCU;
@property (nonatomic, copy) NSString * _Nonnull idBrmForward;
@property (nonatomic, copy) NSString * _Nonnull iEPS;
@property (nonatomic, copy) NSString * _Nonnull iVA;
@property (nonatomic, copy) NSString * _Nonnull maximoAgregar;
@property (nonatomic, copy) NSString * _Nonnull nombreEditable;
@property (nonatomic, copy) NSString * _Nonnull planDescuentoId;
@property (nonatomic, copy) NSString * _Nonnull plazo;
@property (nonatomic, copy) NSString * _Nonnull precioBase;
@property (nonatomic, copy) NSString * _Nonnull precioEditable;
@property (nonatomic, copy) NSString * _Nonnull precioProntoPago;
@property (nonatomic, copy) NSString * _Nonnull productoPadre;
@property (nonatomic, copy) NSString * _Nonnull tipoProducto;
@property (nonatomic, copy) NSString * _Nonnull tipoProductoTexto;
@property (nonatomic, copy) NSString * _Nonnull idProducto;
@property (nonatomic, copy) NSString * _Nonnull nameProducto;
@property (nonatomic, copy) NSString * _Nonnull productoId;
@property (nonatomic, copy) NSString * _Nonnull ciudad;
@property (nonatomic, copy) NSString * _Nonnull velocidadSubida;
@property (nonatomic, copy) NSString * _Nonnull velocidadBajada;
@property (nonatomic, copy) NSString * _Nonnull tieneIPDinamica;
@property (nonatomic, copy) NSString * _Nonnull tieneIPFija;
@property (nonatomic, copy) NSString * _Nonnull tieneSTBAdicional;
@property (nonatomic, copy) NSString * _Nonnull esCCTV;
@property (nonatomic, copy) NSString * _Nonnull esWiFi;
@property (nonatomic, copy) NSString * _Nonnull cantidad;
@property (nonatomic, copy) NSString * _Nonnull estatusProducto;
@property (nonatomic, copy) NSString * _Nonnull fechaInicio;
@property (nonatomic, copy) NSString * _Nonnull fechaFin;
@property (nonatomic, copy) NSString * _Nonnull comentarioProducto;
@property (nonatomic, copy) NSString * _Nonnull priceApp;
@property (nonatomic, copy) NSString * _Nonnull image;
@property (nonatomic) BOOL isSelected;
- (NSArray<NSObject *> * _Nonnull)attributeArray SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)attrbuteTitleSection SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases27ArrProductosConvivenciaBean")
@interface ArrProductosConvivenciaBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Id;
@property (nonatomic, copy) NSString * _Nonnull Name;
@property (nonatomic, copy) NSString * _Nonnull Comentario;
@property (nonatomic, copy) NSString * _Nonnull Estatus;
@property (nonatomic, copy) NSString * _Nonnull ProductoId;
@property (nonatomic, copy) NSString * _Nonnull ProductoExcIncId;
@property (nonatomic, copy) NSString * _Nonnull Tipo;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20ArrProductosIncluido")
@interface ArrProductosIncluido : RealmSwiftObject
- (NSString * _Nonnull)getID SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getAdicionalType SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getAdicionalName SWIFT_WARN_UNUSED_RESULT;
- (double)getPrecioBase SWIFT_WARN_UNUSED_RESULT;
- (double)getPrecioProntoPago SWIFT_WARN_UNUSED_RESULT;
- (double)getCantidad SWIFT_WARN_UNUSED_RESULT;
- (double)getIVA SWIFT_WARN_UNUSED_RESULT;
- (double)getIEPS SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nombre;
@property (nonatomic, copy) NSString * _Nonnull agrupacionAddon;
@property (nonatomic, copy) NSString * _Nonnull cantidadDN;
@property (nonatomic, copy) NSString * _Nonnull cantidadTroncal;
@property (nonatomic, copy) NSString * _Nonnull comentario;
@property (nonatomic, copy) NSString * _Nonnull esAutomaticoCiudad;
@property (nonatomic, copy) NSString * _Nonnull esCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull estatus;
@property (nonatomic, copy) NSString * _Nonnull esVisible;
@property (nonatomic, copy) NSString * _Nonnull idBrmArrear;
@property (nonatomic, copy) NSString * _Nonnull idBrmCU;
@property (nonatomic, copy) NSString * _Nonnull idBrmForward;
@property (nonatomic, copy) NSString * _Nonnull iEPS;
@property (nonatomic, copy) NSString * _Nonnull iVA;
@property (nonatomic, copy) NSString * _Nonnull maximoAgregar;
@property (nonatomic, copy) NSString * _Nonnull nombreEditable;
@property (nonatomic, copy) NSString * _Nonnull planDescuentoId;
@property (nonatomic, copy) NSString * _Nonnull plazo;
@property (nonatomic, copy) NSString * _Nonnull precioBase;
@property (nonatomic, copy) NSString * _Nonnull precioEditable;
@property (nonatomic, copy) NSString * _Nonnull precioProntoPago;
@property (nonatomic, copy) NSString * _Nonnull productoPadre;
@property (nonatomic, copy) NSString * _Nonnull tipoProducto;
@property (nonatomic, copy) NSString * _Nonnull idProducto;
@property (nonatomic, copy) NSString * _Nonnull nameProducto;
@property (nonatomic, copy) NSString * _Nonnull productoId;
@property (nonatomic, copy) NSString * _Nonnull ciudad;
@property (nonatomic, copy) NSString * _Nonnull velocidadSubida;
@property (nonatomic, copy) NSString * _Nonnull velocidadBajada;
@property (nonatomic, copy) NSString * _Nonnull tieneIPDinamica;
@property (nonatomic, copy) NSString * _Nonnull tieneIPFija;
@property (nonatomic, copy) NSString * _Nonnull tieneSTBAdicional;
@property (nonatomic, copy) NSString * _Nonnull esCCTV;
@property (nonatomic, copy) NSString * _Nonnull esWiFi;
@property (nonatomic, copy) NSString * _Nonnull cantidad;
@property (nonatomic, copy) NSString * _Nonnull estatusProducto;
@property (nonatomic, copy) NSString * _Nonnull fechaInicio;
@property (nonatomic, copy) NSString * _Nonnull fechaFin;
@property (nonatomic, copy) NSString * _Nonnull comentarioProducto;
@property (nonatomic, copy) NSString * _Nonnull esProntoPago;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class BaseViewController;
@class DataManager;

SWIFT_CLASS("_TtC10BaseClases13BasePresenter")
@interface BasePresenter : NSObject
@property (nonatomic, strong) BaseViewController * _Nonnull mViewController;
@property (nonatomic, strong) DataManager * _Null_unspecified mDataManager;
- (nonnull instancetype)initWithViewController:(BaseViewController * _Nonnull)viewController OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDisappear;
- (void)viewDidDisappear;
- (void)viewDidUnload;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class User;
@class FormalityEntity;
@class BaseResponse;

SWIFT_CLASS("_TtC10BaseClases23BaseEstrategiaPresenter")
@interface BaseEstrategiaPresenter : BasePresenter
@property (nonatomic, strong) User * _Null_unspecified mUser;
@property (nonatomic, strong) FormalityEntity * _Null_unspecified mFormalityEntity;
- (void)viewDidLoad;
- (void)onRequestWs;
- (void)onSuccessLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl response:(BaseResponse * _Nonnull)response;
- (void)onErrorLoadResponseWithRequestUrl:(NSString * _Nonnull)requestUrl messageError:(NSString * _Nonnull)messageError;
- (void)onErrorConnection;
- (nonnull instancetype)initWithViewController:(BaseViewController * _Nonnull)viewController OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC10BaseClases18BaseViewController")
@interface BaseViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, strong) BasePresenter * _Nullable mPresenter;
@property (nonatomic, copy) NSArray<BasePresenter *> * _Null_unspecified mPresenters;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull extras;
@property (nonatomic, copy) NSString * _Nonnull requestValue;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull data;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (BasePresenter * _Nullable)getPresenter SWIFT_WARN_UNUSED_RESULT;
- (NSArray<BasePresenter *> * _Nullable)getPresenters SWIFT_WARN_UNUSED_RESULT;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)onViewControllerResult;
- (void)onViewControllerResultWithParams:(NSDictionary<NSString *, NSString *> * _Nullable)params;
- (void)hideKeyboard;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases28BaseEstrategiaViewController")
@interface BaseEstrategiaViewController : BaseViewController
@property (nonatomic, strong) DataManager * _Null_unspecified mDataManager;
@property (nonatomic, strong) FormalityEntity * _Null_unspecified mFormalityEntity;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases28BaseNavigationViewController")
@interface BaseNavigationViewController : UINavigationController
@property (nonatomic, copy) NSString * _Nonnull requestValue;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull extras;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull data;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10BaseClases16BaseRealmRequest")
@interface BaseRealmRequest : RealmSwiftObject
- (nonnull instancetype)initWithUser:(NSString * _Nonnull)user password:(NSString * _Nonnull)password;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class LoginRequest;

SWIFT_CLASS("_TtC10BaseClases11BaseRequest")
@interface BaseRequest : NSObject
@property (nonatomic, strong) LoginRequest * _Nullable login;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUser:(NSString * _Nonnull)user password:(NSString * _Nonnull)password OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUser:(NSString * _Nonnull)user password:(NSString * _Nonnull)password ip:(NSString * _Nonnull)ip OBJC_DESIGNATED_INITIALIZER;
@end

@class Result;
@class RestFaultElementBean;

SWIFT_CLASS("_TtC10BaseClases12BaseResponse")
@interface BaseResponse : NSObject
@property (nonatomic, strong) Result * _Nullable resultObj;
@property (nonatomic, copy) NSString * _Nonnull result;
@property (nonatomic, copy) NSString * _Nonnull resultDescription;
@property (nonatomic, copy) NSString * _Nonnull idResult;
@property (nonatomic, strong) RestFaultElementBean * _Nullable restFaultElement;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases24BaseTabBarViewController")
@interface BaseTabBarViewController : UITabBarController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@class LastBillBalance;

SWIFT_CLASS("_TtC10BaseClases11BillingInfo")
@interface BillingInfo : NSObject
@property (nonatomic, strong) LastBillBalance * _Nullable lastBillBalance;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases4Card")
@interface Card : NSObject
@property (nonatomic, copy) NSString * _Nonnull idCard;
@property (nonatomic, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, copy) NSString * _Nonnull expirationMonth;
@property (nonatomic, copy) NSString * _Nonnull expirationYear;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull owner;
@property (nonatomic, copy) NSString * _Nonnull ccType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases9CardsEnum")
@interface CardsEnum : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull VISA;)
+ (NSString * _Nonnull)VISA SWIFT_WARN_UNUSED_RESULT;
+ (void)setVISA:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull MASTER_CARD;)
+ (NSString * _Nonnull)MASTER_CARD SWIFT_WARN_UNUSED_RESULT;
+ (void)setMASTER_CARD:(NSString * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10ClientData")
@interface ClientData : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable zipCode;
@property (nonatomic, copy) NSString * _Nullable colony;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_CLASS("_TtC10BaseClases10ColorUtils")
@interface ColorUtils : NSObject
+ (UIColor * _Nonnull)HexWithRgbValue:(uint32_t)rgbValue alpha:(double)alpha SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12ContactoBean")
@interface ContactoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull TipoPersona;
@property (nonatomic, copy) NSString * _Nonnull Nombre;
@property (nonatomic, copy) NSString * _Nonnull ApellidoPaterno;
@property (nonatomic, copy) NSString * _Nonnull ApellidoMaterno;
@property (nonatomic, copy) NSString * _Nonnull Telefono;
@property (nonatomic, copy) NSString * _Nonnull OtroTelefono;
@property (nonatomic, copy) NSString * _Nonnull Celular;
@property (nonatomic, copy) NSString * _Nonnull CorreoElectronico;
@property (nonatomic, copy) NSString * _Nonnull OtroCorreoElectronico;
@property (nonatomic, copy) NSString * _Nonnull RFC;
@property (nonatomic, copy) NSString * _Nonnull RazonSocial;
@property (nonatomic, copy) NSString * _Nonnull MedioContacto;
@property (nonatomic, copy) NSString * _Nonnull FechaNacimiento;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20CotPlanPromocionBean")
@interface CotPlanPromocionBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases19CotPlanServicioBean")
@interface CotPlanServicioBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull CategoriaServicio;
@property (nonatomic, copy) NSString * _Nonnull DN_Principal;
@property (nonatomic, copy) NSString * _Nonnull DNsActivados;
@property (nonatomic, copy) NSString * _Nonnull DP_PlanServicio;
@property (nonatomic, copy) NSString * _Nonnull EsServicioAdicional;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacion;
@property (nonatomic, copy) NSString * _Nonnull IdExterno_ws;
@property (nonatomic, copy) NSString * _Nonnull IpFijasActivadas;
@property (nonatomic, copy) NSString * _Nonnull NombrePlan;
@property (nonatomic, copy) NSString * _Nonnull NombreServicio;
@property (nonatomic, copy) NSString * _Nonnull SRV_Mode;
@property (nonatomic, copy) NSString * _Nonnull Tipo;
@property (nonatomic, copy) NSString * _Nonnull DP_PromocionPlan;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases23CotServicioProductoBean")
@interface CotServicioProductoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Cantidad;
@property (nonatomic, copy) NSString * _Nonnull CantidadDN;
@property (nonatomic, copy) NSString * _Nonnull CantidadTroncal;
@property (nonatomic, copy) NSString * _Nonnull Descuento;
@property (nonatomic, copy) NSString * _Nonnull DP_Producto;
@property (nonatomic, copy) NSString * _Nonnull DP_PromocionServicioProducto;
@property (nonatomic, copy) NSString * _Nonnull DP_ServicioProducto;
@property (nonatomic, copy) NSString * _Nonnull EsCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull EsDescuento;
@property (nonatomic, copy) NSString * _Nonnull EsProductoAdicional;
@property (nonatomic, copy) NSString * _Nonnull EsProntoPago;
@property (nonatomic, copy) NSString * _Nonnull EsServicioRepetido;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacion;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacionDescripcion;
@property (nonatomic, copy) NSString * _Nonnull FechaFin;
@property (nonatomic, copy) NSString * _Nonnull FechaInicio;
@property (nonatomic, copy) NSString * _Nonnull GeneraDNs;
@property (nonatomic, copy) NSString * _Nonnull Impuesto2;
@property (nonatomic, copy) NSString * _Nonnull Impuesto1;
@property (nonatomic, copy) NSString * _Nonnull MontoImpuestos;
@property (nonatomic, copy) NSString * _Nonnull NombreProducto;
@property (nonatomic, copy) NSString * _Nonnull PrecioUnitario;
@property (nonatomic, copy) NSString * _Nonnull PrecioUnitario_ProntoPago;
@property (nonatomic, copy) NSString * _Nonnull PrecioUnitarioBase;
@property (nonatomic, copy) NSString * _Nonnull ProductoPadre;
@property (nonatomic, copy) NSString * _Nonnull TieneIPDinamica;
@property (nonatomic, copy) NSString * _Nonnull TieneIPFija;
@property (nonatomic, copy) NSString * _Nonnull TipoIp;
@property (nonatomic, copy) NSString * _Nonnull TipoProducto;
@property (nonatomic, copy) NSString * _Nonnull VelocidadBajada;
@property (nonatomic, copy) NSString * _Nonnull VelocidadSubida;
@property (nonatomic, copy) NSString * _Nonnull DP_PromocionPlan;
- (nonnull instancetype)initWithArrProductoIncluido:(ArrProductosIncluido * _Nonnull)arrProductoIncluido;
- (nonnull instancetype)initWithArrProductoAdicional:(ArrProductosAdicionales * _Nonnull)arrProductoAdicional;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases16CotSitioPlanBean")
@interface CotSitioPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull DescuentoCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull DescuentoRenta;
@property (nonatomic, copy) NSString * _Nonnull DN_Principal;
@property (nonatomic, copy) NSString * _Nonnull DP_Plan;
@property (nonatomic, copy) NSString * _Nonnull DP_DescuentoLimiteCargoUnico;
@property (nonatomic, copy) NSString * _Nonnull DP_DescuentoLimiteRenta;
@property (nonatomic, copy) NSString * _Nonnull EstatusActivacion;
@property (nonatomic, copy) NSString * _Nonnull NombrePlan;
@property (nonatomic, copy) NSString * _Nonnull PrecioProntoPago;
@property (nonatomic, copy) NSString * _Nonnull Ticket;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases15CreditCardUtils")
@interface CreditCardUtils : NSObject
+ (NSString * _Nonnull)GetTypeCardWithCard:(NSString * _Nonnull)card SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)GetIdTypeCardWithCard:(NSString * _Nonnull)card SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases19DPPromocionPlanBean")
@interface DPPromocionPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Id;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18DPServicioProducto")
@interface DPServicioProducto : RealmSwiftObject
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class Transactions;

SWIFT_CLASS("_TtC10BaseClases11DataManager")
@interface DataManager : NSObject
@property (nonatomic, strong) Transactions * _Nullable mTransactions;
- (DataManager * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT;
- (void)deleteFormalityEntity;
- (void)txWithExecute:(SWIFT_NOESCAPE void (^ _Nonnull)(Transactions * _Nonnull))execute;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases9DateUtils")
@interface DateUtils : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull dateFormat;)
+ (NSString * _Nonnull)dateFormat SWIFT_WARN_UNUSED_RESULT;
+ (void)setDateFormat:(NSString * _Nonnull)value;
+ (NSString * _Nonnull)toStringWithDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDateNow SWIFT_WARN_UNUSED_RESULT;
+ (NSDate * _Nonnull)toDateWithDate:(NSString * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)toStringWithFormat:(NSString * _Nonnull)format date:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
+ (NSDate * _Nonnull)addingDaysWithDate:(NSDate * _Nonnull)date value:(NSInteger)value SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDateWithDate:(NSString * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20DatosAdicionalesBean")
@interface DatosAdicionalesBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull TipoIdentificacion;
@property (nonatomic, copy) NSString * _Nonnull IdentificacionOficial;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11DeviceUtils")
@interface DeviceUtils : NSObject
+ (NSString * _Nonnull)devideID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13DireccionBean")
@interface DireccionBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull zipCode;
@property (nonatomic, copy) NSString * _Nonnull colony;
@property (nonatomic, copy) NSString * _Nonnull delegation;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull street;
@property (nonatomic, copy) NSString * _Nonnull noExt;
@property (nonatomic, copy) NSString * _Nonnull noInt;
@property (nonatomic, copy) NSString * _Nonnull betweenStreets;
@property (nonatomic, copy) NSString * _Nonnull ReferenciaUrbana;
@property (nonatomic, copy) NSString * _Nonnull authorizationWhitoutCoverage;
@property (nonatomic, copy) NSString * _Nonnull cluster;
@property (nonatomic, copy) NSString * _Nonnull place;
@property (nonatomic, copy) NSString * _Nonnull district;
@property (nonatomic, copy) NSString * _Nonnull feasibility;
@property (nonatomic, copy) NSString * _Nonnull feasible;
@property (nonatomic, copy) NSString * _Nonnull typeCoverage;
@property (nonatomic, copy) NSString * _Nonnull region;
@property (nonatomic, copy) NSString * _Nonnull idRegion;
@property (nonatomic, copy) NSString * _Nonnull zoneValue;
@property (nonatomic, copy) NSString * _Nonnull latitude;
@property (nonatomic, copy) NSString * _Nonnull longitude;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases24DireccionFacturacionBean")
@interface DireccionFacturacionBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull MismaDireccionInstalacion;
@property (nonatomic, copy) NSString * _Nonnull FolioContrato;
@property (nonatomic, copy) NSString * _Nonnull Calle;
@property (nonatomic, copy) NSString * _Nonnull NumeroExterior;
@property (nonatomic, copy) NSString * _Nonnull NumeroInterior;
@property (nonatomic, copy) NSString * _Nonnull ColoniaCP;
@property (nonatomic, copy) NSString * _Nonnull Colonia;
@property (nonatomic, copy) NSString * _Nonnull DelegacionMunicipio;
@property (nonatomic, copy) NSString * _Nonnull Ciudad;
@property (nonatomic, copy) NSString * _Nonnull Estado;
@property (nonatomic, copy) NSString * _Nonnull CodigoPostal;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18EncryptedLoginBean")
@interface EncryptedLoginBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull user;
@property (nonatomic, copy) NSString * _Nonnull password;
@property (nonatomic, copy) NSString * _Nonnull ip;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class MetodoPagoBean;
@class ReferenciasBean;

SWIFT_CLASS("_TtC10BaseClases9FirmaBean")
@interface FirmaBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, strong) DireccionFacturacionBean * _Nullable DireccionFacturacion;
@property (nonatomic, strong) DatosAdicionalesBean * _Nullable DatosAdicionales;
@property (nonatomic, strong) MetodoPagoBean * _Nullable MetodoPago;
@property (nonatomic, strong) ReferenciasBean * _Nullable Referencias;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class NSMutableArray;

SWIFT_CLASS("_TtC10BaseClases13FormValidator")
@interface FormValidator : NSObject
@property (nonatomic, strong) NSMutableArray * _Nullable validators;
@property (nonatomic) BOOL showAnimationError;
- (nonnull instancetype)initWithShowAllErrors:(BOOL)showAllErrors showAnimationError:(BOOL)showAnimationError OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isValid SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class ProspectoBean;
@class SaleReleaseBean;

SWIFT_CLASS("_TtC10BaseClases15FormalityEntity")
@interface FormalityEntity : BaseRealmRequest
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, strong) ProspectoBean * _Nullable Prospecto;
@property (nonatomic, strong) SaleReleaseBean * _Nullable saleRelease;
@property (nonatomic, strong) EncryptedLoginBean * _Nullable loginBean;
@property (nonatomic) BOOL isUsedIdAsProof;
@property (nonatomic) double totalPriceList;
@property (nonatomic) double totalPriceSoonPayment;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases6Imagen")
@interface Imagen : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull image;
@property (nonatomic, copy) NSString * _Nonnull thumbnail;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull opportunityId;
@property (nonatomic, copy) NSString * _Nonnull brmAccount;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull syncStatus;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11Information")
@interface Information : NSObject
@property (nonatomic, copy) NSString * _Nonnull type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithType:(NSString * _Nonnull)type OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases15LastBillBalance")
@interface LastBillBalance : NSObject
@property (nonatomic, copy) NSString * _Nullable paymentDeadLine;
@property (nonatomic, copy) NSString * _Nullable earlyPaymentDeadline;
@property (nonatomic, copy) NSString * _Nullable cuOffData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12LoginRequest")
@interface LoginRequest : NSObject
@property (nonatomic, copy) NSString * _Nullable user;
@property (nonatomic, copy) NSString * _Nullable password;
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable versionAPP;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUser:(NSString * _Nonnull)user password:(NSString * _Nonnull)password ip:(NSString * _Nonnull)ip OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases14MetodoPagoBean")
@interface MetodoPagoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Metodo;
@property (nonatomic, copy) NSString * _Nonnull TipoTarjeta;
@property (nonatomic, copy) NSString * _Nonnull NombreTitular;
@property (nonatomic, copy) NSString * _Nonnull ApellidoPaternoTitular;
@property (nonatomic, copy) NSString * _Nonnull ApellidoMaternoTitular;
@property (nonatomic, copy) NSString * _Nonnull NumeroTarjeta;
@property (nonatomic, copy) NSString * _Nonnull VencimientoMes;
@property (nonatomic, copy) NSString * _Nonnull VencimientoAnio;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases8NameData")
@interface NameData : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases7NewCard")
@interface NewCard : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull lastName;
@property (nonatomic, copy) NSString * _Nonnull secondLastName;
@property (nonatomic, copy) NSString * _Nonnull cardNumber;
@property (nonatomic, copy) NSString * _Nonnull expirationMonth;
@property (nonatomic, copy) NSString * _Nonnull expirationYear;
@property (nonatomic, copy) NSString * _Nonnull ccType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name lastName:(NSString * _Nonnull)lastName secondLastName:(NSString * _Nonnull)secondLastName cardNumber:(NSString * _Nonnull)cardNumber expirationMonth:(NSString * _Nonnull)expirationMonth expirationYear:(NSString * _Nonnull)expirationYear ccType:(NSString * _Nonnull)ccType OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12PackagesType")
@interface PackagesType : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RESIDENTIAL;)
+ (NSString * _Nonnull)RESIDENTIAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull BUSINESS;)
+ (NSString * _Nonnull)BUSINESS SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSLayoutConstraint;

SWIFT_CLASS("_TtC10BaseClases19PopUpViewController")
@interface PopUpViewController : BaseViewController <UIGestureRecognizerDelegate>
@property (nonatomic, strong) NSLayoutConstraint * _Null_unspecified bottomLeftViewBottomConstraint;
- (void)viewDidLoad;
- (void)keyboardWillShow:(NSNotification * _Nonnull)sender;
- (void)keyboardWillHide:(NSNotification * _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13PropuestaBean")
@interface PropuestaBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Oferta;
@property (nonatomic, copy) NSString * _Nonnull TipoPago;
@property (nonatomic, strong) CotSitioPlanBean * _Nullable Cot_SitioPlan;
@property (nonatomic, strong) CotPlanPromocionBean * _Nullable Cot_PlanPromocion;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class VendedorBean;

SWIFT_CLASS("_TtC10BaseClases13ProspectoBean")
@interface ProspectoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull PlazoContrato;
@property (nonatomic, copy) NSString * _Nonnull CuentaBRM;
@property (nonatomic, copy) NSString * _Nonnull IdOportunidad;
@property (nonatomic, copy) NSString * _Nonnull IdCuenta;
@property (nonatomic, copy) NSString * _Nonnull IdCuentaFactura;
@property (nonatomic, copy) NSString * _Nonnull IdContacto;
@property (nonatomic, copy) NSString * _Nonnull IdCotizacion;
@property (nonatomic, copy) NSString * _Nonnull IdSitio;
@property (nonatomic, strong) VendedorBean * _Nullable Vendedor;
@property (nonatomic, strong) DireccionBean * _Nullable Direccion;
@property (nonatomic, strong) ContactoBean * _Nullable Contacto;
@property (nonatomic, strong) PropuestaBean * _Nullable Propuesta;
@property (nonatomic, strong) FirmaBean * _Nullable Firma;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases15ReferenciasBean")
@interface ReferenciasBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases12ReferidoBean")
@interface ReferidoBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull Nombre;
@property (nonatomic, copy) NSString * _Nonnull ApellidoPaterno;
@property (nonatomic, copy) NSString * _Nonnull ApellidoMaterno;
@property (nonatomic, copy) NSString * _Nonnull Parentesco;
@property (nonatomic, copy) NSString * _Nonnull Telefono;
@property (nonatomic) BOOL isValid;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases8Response")
@interface Response : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable mDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases20RestFaultElementBean")
@interface RestFaultElementBean : NSObject
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull detail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases6Result")
@interface Result : NSObject
@property (nonatomic, copy) NSString * _Nonnull result;
@property (nonatomic, copy) NSString * _Nonnull idResult;
@property (nonatomic, copy) NSString * _Nonnull descriptionValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10ResultBean")
@interface ResultBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull result;
@property (nonatomic, copy) NSString * _Nonnull idResult;
@property (nonatomic, copy) NSString * _Nonnull descript;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases11ResultLogin")
@interface ResultLogin : NSObject
@property (nonatomic, copy) NSString * _Nonnull accountNumber;
@property (nonatomic, copy) NSString * _Nonnull result;
@property (nonatomic, copy) NSString * _Nonnull idResult;
@property (nonatomic, copy) NSString * _Nonnull descriptionValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TipoPlanBean;

SWIFT_CLASS("_TtC10BaseClases15SaleReleaseBean")
@interface SaleReleaseBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, strong) TipoPlanBean * _Nullable typePlain;
@property (nonatomic, strong) ArrPlanBean * _Nullable plainBean;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

SWIFT_CLASS("_TtC10BaseClases9Validator")
@interface Validator : NSObject
@property (nonatomic, strong) UIView * _Null_unspecified view;
- (BOOL)isValid SWIFT_WARN_UNUSED_RESULT;
- (void)showErrorWithValid:(BOOL)valid;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UISegmentedControl;

SWIFT_CLASS("_TtC10BaseClases25SegmentedControlValidator")
@interface SegmentedControlValidator : Validator
@property (nonatomic, copy) NSArray<Validator *> * _Nonnull mValidators;
@property (nonatomic, strong) UISegmentedControl * _Null_unspecified mSegmentedControl;
@property (nonatomic) NSInteger mPositionValue;
- (BOOL)isValid SWIFT_WARN_UNUSED_RESULT;
- (void)showErrorWithValid:(BOOL)valid;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases10Statements")
@interface Statements : NSObject
@property (nonatomic, copy) NSString * _Nonnull date;
@property (nonatomic, copy) NSString * _Nonnull balance;
@property (nonatomic, copy) NSString * _Nonnull url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases13StringDialogs")
@interface StringDialogs : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dialog_error_connection;)
+ (NSString * _Nonnull)dialog_error_connection SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dialog_error_intern;)
+ (NSString * _Nonnull)dialog_error_intern SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dialog_error_empty;)
+ (NSString * _Nonnull)dialog_error_empty SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dialog_error_expiration_date;)
+ (NSString * _Nonnull)dialog_error_expiration_date SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dialog_error_empty_fields;)
+ (NSString * _Nonnull)dialog_error_empty_fields SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dialog_error_empty_fields_new;)
+ (NSString * _Nonnull)dialog_error_empty_fields_new SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull dialog_success_save_new_card;)
+ (NSString * _Nonnull)dialog_success_save_new_card SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10SyncStatus")
@interface SyncStatus : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull NOT_SYNCHRONIZED;)
+ (NSString * _Nonnull)NOT_SYNCHRONIZED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SYNCHRONIZING;)
+ (NSString * _Nonnull)SYNCHRONIZING SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SYNCHRONIZED;)
+ (NSString * _Nonnull)SYNCHRONIZED SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases5Terms")
@interface Terms : NSObject
@property (nonatomic, copy) NSString * _Nullable offset;
@property (nonatomic, copy) NSString * _Nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18TextFieldValidator")
@interface TextFieldValidator : Validator
@property (nonatomic, strong) UITextField * _Null_unspecified textField;
@property (nonatomic, copy) NSString * _Nonnull messageError;
@property (nonatomic, strong) NSLayoutConstraint * _Nullable constraintBottom;
@property (nonatomic) NSInteger minCharacters;
@property (nonatomic) NSInteger maxCharacters;
@property (nonatomic) BOOL required;
@property (nonatomic, copy) NSString * _Nonnull valueText;
@property (nonatomic) NSInteger year;
@property (nonatomic, readonly) CGFloat width;
- (nonnull instancetype)initWithTextField:(UITextField * _Nonnull)textField regex:(NSInteger)regex messageError:(NSString * _Nonnull)messageError OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTextField:(UITextField * _Nonnull)textField regex:(NSInteger)regex OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTextField:(UITextField * _Nonnull)textField regex:(NSInteger)regex year:(NSInteger)year messageError:(NSString * _Nonnull)messageError OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTextField:(UITextField * _Nonnull)textField minCharacters:(NSInteger)minCharacters maxCharacters:(NSInteger)maxCharacters messageError:(NSString * _Nonnull)messageError OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTextField:(UITextField * _Nonnull)textField regex:(NSInteger)regex minCharacters:(NSInteger)minCharacters maxCharacters:(NSInteger)maxCharacters messageError:(NSString * _Nonnull)messageError OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTextField:(UITextField * _Nonnull)textField regex:(NSInteger)regex valueText:(NSString * _Nonnull)valueText OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isValid SWIFT_WARN_UNUSED_RESULT;
- (void)showErrorWithValid:(BOOL)valid;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases12TipoPlanBean")
@interface TipoPlanBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nullable tipo;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(BaseClases))
- (nonnull instancetype)initWithRed:(NSInteger)red green:(NSInteger)green blue:(NSInteger)blue;
- (nonnull instancetype)initWithNetHex:(NSInteger)netHex;
@end






SWIFT_CLASS("_TtC10BaseClases4User")
@interface User : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull accountNumber;
- (nonnull instancetype)initWithAccountNumber:(NSString * _Nonnull)accountNumber;
+ (NSString * _Nonnull)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases10UserPassIp")
@interface UserPassIp : NSObject
@property (nonatomic, copy) NSString * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable ip;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId password:(NSString * _Nonnull)password ip:(NSString * _Nonnull)ip OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC10BaseClases12VendedorBean")
@interface VendedorBean : RealmSwiftObject
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull IdEmpleado;
@property (nonatomic, copy) NSString * _Nonnull Canal;
@property (nonatomic, copy) NSString * _Nonnull SubCanal;
@property (nonatomic, copy) NSString * _Nonnull FolioContrato;
@property (nonatomic, copy) NSString * _Nonnull IdDispositivo;
@property (nonatomic, copy) NSString * _Nonnull IdDistrital;
@property (nonatomic, copy) NSString * _Nonnull IdEmpleadoDistrital;
@property (nonatomic, copy) NSString * _Nonnull OrigenApp;
@property (nonatomic, copy) NSString * _Nonnull EsComisionable;
@property (nonatomic, copy) NSString * _Nonnull IMEI;
@property (nonatomic, copy) NSString * _Nonnull ModeloCelular;
@property (nonatomic, copy) NSString * _Nonnull EmpleadoDistribuidor;
@property (nonatomic, copy) NSString * _Nonnull UsuarioLogueado;
@property (nonatomic, copy) NSString * _Nonnull aprobarVentaExpress;
@property (nonatomic, copy) NSString * _Nonnull ventaExpress;
+ (NSString * _Nullable)primaryKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRealm:(RLMRealm * _Nonnull)realm schema:(RLMObjectSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithValue:(id _Nonnull)value schema:(RLMSchema * _Nonnull)schema OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10BaseClases18ViewGroupValidator")
@interface ViewGroupValidator : Validator
@property (nonatomic, strong) Validator * _Null_unspecified validator;
@property (nonatomic, copy) NSArray<Validator *> * _Nonnull validators;
@property (nonatomic) BOOL showAllErrors;
@property (nonatomic) BOOL valueActivator;
- (nonnull instancetype)initWithValidator:(Validator * _Nonnull)validator validators:(NSArray<Validator *> * _Nonnull)validators showAllErrors:(BOOL)showAllErrors valueActivator:(BOOL)valueActivator OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isValid SWIFT_WARN_UNUSED_RESULT;
- (void)showErrorWithValid:(BOOL)valid;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10BaseClases9ViewUtils")
@interface ViewUtils : NSObject
+ (void)addSubviewWithSubView:(UIView * _Nonnull)subView toView:(UIView * _Nonnull)parentView;
+ (void)cycleFromViewControllerWithViewController:(UIViewController * _Nonnull)viewController inContainerView:(UIView * _Nonnull)containerView fromOldViewController:(UIViewController * _Nonnull)oldViewController toViewController:(UIViewController * _Nonnull)newViewController;
+ (BOOL)isGoneWithView:(UIView * _Nonnull)view SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
